### ISSUE TITLE
support graphql@14.0.0

### ISSUE THREAD

**Issue by zhenyulin** [neo4j-graphql/neo4j-graphql-js#100]
graphql@14.0.0 just got released: https://github.com/graphql/graphql-js/releases/tag/v14.0.0

after upgrade to this version, it is throwing error of unknown directive @relation

we may want to specify peerDependencies to lock the graphql-js version for now

**Comment by johnymontana** [comment]
It seems in graphql v14.0.0 we must explicitly add new directives to the schema object for proper schema validation. 

I don't believe we encountered this issue when we tested against graphql v14.0.0-rc2. Please use graphql@0.13.x until we fix this (note that graphql-js has also changed versioning schemes with this release)

@zhenyulin Are you using graphql-js explicitly alongside neo4j-graphql-js? I'm curious what your use case is there.

**Comment by eljenso** [comment]
@johnymontana `apollo-server` has `graphql` as peerDependencies
See: https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server/package.json

**Comment by johnymontana** [comment]
graphql-js dependency has been upgraded to v14.x
