### ISSUE TITLE
Same label add relationship mutation only includes one ID param for auto-gen mutation

### ISSUE THREAD

**Issue by johnymontana** [neo4j-graphql/neo4j-graphql-js#102]
When auto-generating the add relationship mutation using augmentSchema for a relationship where the from and to nodes have the same label, only one ID parameter is included in the mutation. For example:

```
type Department {
  id: ID!
  name: String
  level: Int
  children: [Department] @relation(name: "CHILD_DEPT", direction: "OUT")
  parents: [Department] @relation(name: "CHILD_DEPT", direction: "IN")
}
```

auto-gens the following mutation:

```
AddDepartmentChildren(departmentid: ID!): Department
```

instead, the mutation should include 2 IDs, something like:

```
AddDepartmentChildren(fromDepartmentid: ID!, toDepartmentid: ID!): Department
```

**Comment by shreyansh-zazz** [comment]
Status??? @johnymontana

**Comment by johnymontana** [comment]
This has been fixed by the updates to the relation type API and the addition of `to` and `from` arguments that use generated input types.
