### ISSUE TITLE
Auto Generated Mutations don't include any custom Scalars

### ISSUE THREAD

**Issue by Murcho** [neo4j-graphql/neo4j-graphql-js#109]
Using the definition 

    scalar DateTime

    type Receipt {
        receiptData: String,
        expiryDate: DateTime,
        lastValidation: DateTime,
        status: String
    }

only generates the CreateReceipt mutation with the following arguments 

    CreateReceipt(receiptData:String!, status:String): Receipt

I can manually generate the mutation by adding the definition

    type Mutation {
        CreateReceiptDated(receiptData: String, expriyDate: DateTime, lastValidation:  DateTime, status: String): Receipt
    }

and then creating the following resolvers

    resolvers = {
        DateTime: GraphQLDateTime,
        Mutation: {
            CreateReceiptDated(object, params, ctx, resolveInfo) {
                return neo4jgraphql(object, params, ctx, resolveInfo, true);
            }
        }
    };

The auto generated mutation should include the custom scalar in the signature.

**Comment by appinteractive** [comment]
Was it fixed with the latest pr?

**Comment by johnymontana** [comment]
@appinteractive yes, this has been fixed. You can see this working [in the augment schema tests](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/test/augmentSchemaTest.js#L250-L251)

Please let us know if it isn't working for you.
