### ISSUE TITLE
Provide possibility to set/change/validate field argument before data are fetched

### ISSUE THREAD

**Issue by crmue** [neo4j-graphql/neo4j-graphql-js#112]
Given is the following basic schema:

```
type User {
  name: String!
  elements: [Element] @relation(name:"OWNER", direction:"OUT")
}

type Element {
  uuid: String!
  name: String
  users: [User] @relation(name:"OWNER", direction:"IN")
  tags: [Tag] @relation(name:"TAGGED", direction:"IN")
  responses: [Element] @relation(name:"RESPONSE", direction:"OUT")
}

type Tag {
  name: String!
  elements(username:String! @usercheck) : [Element] @cypher(statement: "MATCH (this)-[:TAGGED]-(e:Element)-[:OWNER]-(u:User) WHERE u.name=$username RETURN e")
}
```
The used `@cypher` directive of field `elements` within `Tag` requires the argument `username`. I need to verify and maybe change the given argument value,  before root resolver fetches the data from database.
The field resolvers and the directive `@usercheck` are called after the data are already fetched. 

I can easily add/change an argument within the root `Tag` resolver, but the same possibility for fields would be great. Currently I solve this by filtering the resolver info selections, but the argument is only available when defined as mandatory in schema and given by the query. A default field argument e.g. `elements(username:String = "xdummyuserx")` is not contained in the resolverInfo.

**Comment by johnymontana** [comment]
Since neo4j-graphql.js generates a single Cypher query for the entire GraphQL request (even for these computed fields) the field level resolver is not even called.

The recommended approach would be to implement a resolver for this field so you can include the validation logic there. However, we don't yet have a way to mark fields as "external" to be ignored by the query generation process. So #34 will need to be implemented before this approach will work.

**Comment by smkhalsa** [comment]
@crmue have you considered [middleware](https://github.com/prisma/graphql-middleware)?

**Comment by johnymontana** [comment]
The recommended solution here would be to implement a field level resolver for `elements`, you could also take a look at the [authorization schema directives](https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization.html#graphql-authorization-schema-directives) to see if those address your use case.
