### ISSUE TITLE
Auto Generated Mutations don't include scalar type Lists 

### ISSUE THREAD

**Issue by metarama** [neo4j-graphql/neo4j-graphql-js#121]
type Person {
  name: String
  emails: [String]
}
auto generates mutation:

  CreatePerson(name: String)

instead of:

  CreatePerson(name: String, emails: [String])

This is similar to #109.

**Comment by johnymontana** [comment]
Very similar to #74

**Comment by wimklerkx** [comment]
+1
I'm also running into this issue. Is there a solution on the horizon yet?

**Comment by smkhalsa** [comment]
@johnymontana will this make it into the next sprint?

**Comment by johnymontana** [comment]
This has been fixed, as demonstrated in the [schema augmentation tests](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/test/augmentSchemaTest.js#L469) and the [Cypher generation tests](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/test/cypherTest.js#L3620-L3672)

But please re-open if you continue to see this problem.
