### ISSUE TITLE
Accessing auto-generated queries and mutations not in a tag

### ISSUE THREAD

**Issue by behemothdan** [neo4j-graphql/neo4j-graphql-js#123]
I am not sure if I am missing this in the documentation but I would like to be able to access the auto-generated mutations and queries without using graphql-tag.

As an example, I have a number of graphql queries I wrote when using an earlier version of neo4j-graphql-js that are no longer needed. I am augmenting the schema and I can see the auto-generated queries as well as the ones I wrote myself in the GraphQL playground.

I would compose my React component with something like this:

`    graphql(CREATE_RECIPE_INGREDIENTS, { name: 'CreateIngredientRelation' }),
`

After importing the 'CREATE_RECIPE_INGREDIENTS' at the top of the component. I could then call this mutation without having to use graphql-tag.

```
            this.props.CreateIngredientRelation({
                variables: {
                    name: ingredient.name,
                    recipe: recipe.data.CreateRecipe.name,
                    quantity: ingredient.quantity.trim()
                }
            })
```

Is there a way to accomplish something similar with the auto-generated queries/mutations? The new auto-generated queries work as I've tested them in the graphql playground but I want to be able to call them from non-tag places in my code. Can I do this or should I stick with my hand-written ones for now? Thanks!

**Comment by johnymontana** [comment]
Hey @behemothdan - I'm not sure exactly what you're suggesting. It sounds like you are describing some sort of client side code generation. Or some sort of client side library that knows the conventions used for the generated mutations based on the types? Something like this library perhaps: https://github.com/dotansimha/graphql-code-generator ?

**Comment by behemothdan** [comment]
I apologize for leaving this issue open. My problem stemmed from my own disconnect of the interaction between the front and back-end of my project rather than a lack of a feature I was hoping for.
