### ISSUE TITLE
Feature Request: Union type support

### ISSUE THREAD

**Issue by NatElkins** [neo4j-graphql/neo4j-graphql-js#130]
See https://graphql.org/learn/schema/#union-types

I may be able to put some time into this through my job.  Do you have any idea of the approximate scale of the work required?  Any pointers in the right direction would be deeply appreciated.

Thanks, really amazing project!

**Comment by obarbier** [comment]
I agree, This a huge feature and given that work on in line fragments has started, we should work in parallel to get this feature implemented.

**Comment by whostolebenfrog** [comment]
@johnymontana Is this something that's being worked on? I'm considering whether or not to try and make a PR but really don't want to do so if it's already in progress.

I'm imaging that this is a fairly big change - is it something you would realistically be comfortable merging from someone external?

Many thanks!

**Comment by johnymontana** [comment]
Support for unions using multiple labels was added in v2.13.0. See the docs here: https://grandstack.io/docs/graphql-interface-union-types.html#union-types
