### ISSUE TITLE
Querying for non existing record throws an error, is this intended?

### ISSUE THREAD

**Issue by deep-c** [neo4j-graphql/neo4j-graphql-js#14]
Hi,

Ive been trying out this library and when the following query gets resolved `MATCH (user:User {username:"cvcv"}) RETURN user { .username , .password } AS user SKIP 0` an error of `TypeError: Cannot read property 'get' of undefined` is thrown. Obviously it due to the fact that there is no check for an empty array here:
```
//function neo4jgraphql
    } else if (returnType === returnTypeEnum.OBJECT) {
      return result.records[0].get(variable);
    }
```
resulting in the following graphql response
```
{
  "data": {
    "userByUsername": null
  },
  "errors": [
    {
      "message": "Cannot read property 'get' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "userByUsername"
      ]
    }
  ]
}
```

I would expect null (or an empty object) to be returned with no error (the error doesnt seem appropriate to me). I'm just wondering if this is regarded as expected behaviour?

Thanks

**Comment by johnymontana** [comment]
Thanks for reporting @deep-c! You are correct, the error is not appropriate here. I believe null is the correct response here.
