### ISSUE TITLE
Custom resolveType ignored

### ISSUE THREAD

**Issue by purplemana** [neo4j-graphql/neo4j-graphql-js#141]
Referring to this sample repo: https://github.com/purplemana/neo4j-graphql-exp, there's a custom resolverType which resolves interface `User` implementations. The code works if the schema is not augmented. Once it is augmented, `User.__resolveType` resolver is not invoked anymore resulting in a GraphQL error.

To reproduce:
1. Optional: change Neo4J credentials mentioned at: https://github.com/purplemana/neo4j-graphql-exp/blob/master/src/index.js#L12
2. Change https://github.com/purplemana/neo4j-graphql-exp/blob/master/src/index.js#L8 to remove the call to `augmentSchema`.
3. Run the code and invoke `users` query. Note that the results are being returned.
4. Put the `augmentSchema` call back.
5. Run the code and notice that this error shows up:

>"Abstract type User must resolve to an Object type at runtime for field Query.users with value { id: \"One\", type: \"CustomUser\", fullName: \"One\", email: \"One\", enabled: true, emailVerified: true }, received \"undefined\". Either the User type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function."

6. Also notice that `__resolveType` is not invoked this time.

Is there a different way to implement interface based types with this package?

**Comment by btroop** [comment]
Running into a similar issue. Have added/removed __resolveType resolvers, as well as followed Apollo documentation for adding schema to client cache.

I've received that exact error, and I've also received the following error, depending on presence of __resolveType functions.

```
"Error: Resolve function for \"Organization.commonName\" returned undefined",
```

[Apollo guidance - Unions & interfaces](https://www.apollographql.com/docs/graphql-tools/resolvers.html#Unions-and-interfaces)


[Apollo guidance - Fragment matcher](https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher)

Does neo4j-graphql-js support interfaces? If so, what's the guidance for making them work?

**Comment by tungv** [comment]
If you want to query an interface with relationships in fragment, you can query the node first to see which other label it has, and then query again with that label.

For convenience, I use the following function to query by label and id, then reuse selectionSet from the original query:

```js
const { neo4jgraphql } = require("neo4j-graphql-js");

module.exports = async function getOneNodeWithSelections(label, id, ctx, info) {
  const rInfo = {
    schema: info.schema,
    fieldName: label,
    fieldNodes: [
      {
        kind: "Field",
        name: {
          kind: "Name",
          value: label,
        },
        arguments: [
          {
            kind: "Argument",
            name: {
              kind: "Name",
              value: "id",
            },
            value: {
              kind: "Variable",
              name: {
                kind: "Name",
                value: "id",
              },
            },
          },
        ],
        directives: [],
        selectionSet: info.fieldNodes[0].selectionSet,
      },
    ],
    returnType: label,
    parentType: "Query",
    path: "Query",
    fragments: info.fragments,
    operation: {
      kind: "OperationDefinition",
      operation: "query",
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: {
              kind: "Name",
              value: label,
            },
            arguments: [
              {
                kind: "Argument",
                name: {
                  kind: "Name",
                  value: "id",
                },
                value: {
                  kind: "Variable",
                  name: {
                    kind: "Name",
                    value: "id",
                  },
                },
              },
            ],
            directives: [],
            selectionSet: info.fieldNodes[0].selectionSet,
          },
        ],
      },
    },
  };

  return neo4jgraphql({}, { id }, ctx, rInfo);
};
```

And you can write the interface resolver as follow, (given `Node` is the interface name)

```js
exports.Query = {
  async Node(_, { id }, { driver }, info) {
    const query = /* cypher */ `
    MATCH (n:Node {id: $id}) RETURN labels(n) as labels;
    `;

    const session = driver.session();
    const resp = await session.run(query, { id });
    const [record] = resp.records;

    if (!record) {
      return null;
    }

    const labels = record.get("labels");
    const FRAGMENT_TYPE = labels.find(l => l !== "Node");

    const r = await getOneNodeWithSelections(
      FRAGMENT_TYPE,
      id,
      { driver },
      info
    );
    return {
      ...r,
      FRAGMENT_TYPE, // this is important because neo4j-graphql uses this attr to resolve type by default
    };
  },
};
```

This takes 2 queries for one node. However, if you have only one fragment spread, you can probably use that fragment condition to eliminate the first query.

**Comment by johnymontana** [comment]
`__resolveType` resolvers are now generated during the schema augmentation process based on using multiple labels in Neo4j.

Please see the docs for an example of how interfaces can be used: https://grandstack.io/docs/graphql-interface-union-types.html

**Comment by c0dification** [comment]
@johnymontana Does the schema augmentation process do this even when there are 3 or more labels on the node? 

For example, I have a node with one label "Equipment" which represents the data type. Then I have two other labels, "EventResource" and "EventActivity" which I added to support graphql interfaces. However, it is not working. I'm still getting the error: 
```
"message": "Abstract type EventResource must resolve to an Object type at runtime for field Query.EventResource with value { name: \"heavy lifting\", FRAGMENT_TYPE: null, id: \"IWSpxQvnMpSbnaSsmGAT\" }, received \"null\". Either the EventResource type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function."
```
