### ISSUE TITLE
Unexpected relation behavior with same types

### ISSUE THREAD

**Issue by mindbogglegames** [neo4j-graphql/neo4j-graphql-js#148]
I am trying to model a person liking another person or organization. I have set up the following type and relation

`
type Person {
    uuid: ID!
    name: String
    likes_person: [LikesPerson!]
    likes_organization: [LikesOrganization!]
  }
`

`
type LikesPerson @relation(name: "LIKES") {
    from: Person
    to: Person
  }
`

`
type LikesOrganization @relation(name: "LIKES") {
    from: Person
    to: Organization
 }
`

The following query works fine for fetching relation to organization
`
Person(uuid: "830bf813")
  {
    name
    likes_organization{
      Organization{
        name
        uuid
      }
    }
  }
`

But this query does not work for fetching relation to another person
`
Person(uuid: "830bf813")
  {
    name
    likes_person{
      Person{
        name
        uuid
      }
    }
  }
`
Error produced: 
`
"message": "Cannot query field \"Person\" on type \"_PersonLikes_personDirections\".",
`

Is this due to both from and to being of the type Person? I am using makeAugmentedSchema

**Comment by cprakti** [comment]
Was this ever resolved? Trying to do something similar.
I'm getting an error that says `"Expected to find a node at ref slot 1 but found -[22]- instead"`

**Comment by mindbogglegames** [comment]
In the case where both Entities are of the same type the return object changes. In that case the object returned has a "to" and "from" object. To will contain what the relation points to and from where the relation is pointing from

Not super clean. Also undocumented last time I checked.

**Comment by rdimicheleb** [comment]
Tip/advice:
When the object changes like @mindbogglegames said, the properties of the relationships moves inside `from`.

**Comment by aonamrata2** [comment]
Thanks @mindbogglegames , I was still at the basic problem of how to get field values from the `to` relationship. ` Person(uuid: "830bf813") { name likes_organization{ Organization{ name uuid } } }` this helped.
