### ISSUE TITLE
Multiple labels for interface types

### ISSUE THREAD

**Issue by smkhalsa** [neo4j-graphql/neo4j-graphql-js#150]
In my schema I've defined a type that implements an interface. When I use the generated mutation to create a node of that type, the resulting node only includes a label of the specified type, not a label of the interface type. I would expect it to have both labels.

**Comment by wimklerkx** [comment]
I would expect a similar mechanism for **Union** types

**Comment by flazoon** [comment]
This should be fixed by https://github.com/neo4j-graphql/neo4j-graphql-js/pull/336

**Comment by johnymontana** [comment]
Closing as this was fixed in #336 - please reopen if you're still seeing this behavior.
