### ISSUE TITLE
Support for subscription types in schema

### ISSUE THREAD

**Issue by NathanPimlott** [neo4j-graphql/neo4j-graphql-js#153]
Is there any support for subscriptions in schema definition? Using Apollo Server, express and neo4j-graphql-js trying to implement subscriptions. Can anyone provide any pointers or tips for getting this to work?

Thanks

**Comment by appinteractive** [comment]
Have you tried GraphQL-yoga already instead of Apollo-Server? https://github.com/prisma/graphql-yoga

**Comment by NathanPimlott** [comment]
I have not. I will give that a try now, thanks.

**Comment by NathanPimlott** [comment]
I have give that a go and its working perfectly. Thanks for the help @appinteractive , much appreciated

**Comment by erikrahm** [comment]
@NathanPimlott what did you change to make subscriptions work exactly? I'm having some trouble.
