### ISSUE TITLE
augmented schema doesn't augment Arrays of basic types

### ISSUE THREAD

**Issue by jonathanhuet** [neo4j-graphql/neo4j-graphql-js#156]
Hi,

When declaring a type like the following:
`type Human {`
`  id: ID,`
` name: String,`
` nicknames: [String],`
` preferredIntegers: [Int],`
` preferredFloads: [Float]`
`}`

**Current behavior:**
The augmented schema doesn't support the properties that are arrays of a basic type. Then they are not added to the CreateXXX or UpdateXXX

This is the result on the playground:
![image](https://user-images.githubusercontent.com/20546455/49660682-84a79f80-fa47-11e8-83ea-3f32a2ad5bb1.png)

**Expected behavior:**
Nicknames, preferredIntegers, preferredFoads properties should appear in the CreateXXX operation

**Comment by johnymontana** [comment]
This has been fixed in v2.1.0. Please test and reopen if you are still having issues.
