### ISSUE TITLE
[Bug] Adding ! (required) to a DateTime Field, throw an error

### ISSUE THREAD

**Issue by Kitefr** [neo4j-graphql/neo4j-graphql-js#158]
I tried temporal field a bit and i noticed than adding a required to a Temporal Field actually throw an Error.

```graphql
type Movie {
   title: String
   createdAt: DateTime!  // Throw an error !
}
```

The error is : 
`Cannot read property '0' of undifined`.

Can some replicate this issue ?

**Comment by michaeldgraham** [comment]
Hi @Kitefr, thanks for reporting this! I have replicated the issue and will be working on fixing it soon :)

**Comment by Kitefr** [comment]
Thanks you :)
