### ISSUE TITLE
2.1.0 breaks interfaces with non-null fields

### ISSUE THREAD

**Issue by smkhalsa** [neo4j-graphql/neo4j-graphql-js#166]
After updating to v2.1.0 I get the following error when I start my server:

`Interface field SongCollection.name expects type String! but UserPlaylist.name is type String.`

Here's my schema. As you can see, the name property is non-null in both the SongCollection interface and the UserPlaylist type.

```
interface SongCollection {
  id: ID!
  name: String!
  songs: [Song!]! @relation(name: "HAS_SONG", direction: "OUT")
}

type UserPlaylist implements SongCollection {
  id: ID!
  name: String!
  songs: [Song!]! @relation(name: "HAS_SONG", direction: "OUT") # Define sort order
  owner: User! @relation(name: "CREATED_BY", direction: "OUT") # Define sort order
}
```

I assume it's related to [this change.](https://github.com/neo4j-graphql/neo4j-graphql-js/pull/161/commits/d74cc4f4dbb02c08be226fd8b681b997b7c4df68)

**Comment by smkhalsa** [comment]
@michaeldgraham any ideas on this?

**Comment by smkhalsa** [comment]
After further investigation, it looks like in 2.1.0 the augment function is converting all required scalars to optional in each of my types, not just types that implement an interface.

**Comment by michaeldgraham** [comment]
I'll look into this as soon as possible, definitely shouldn't be happening

**Comment by michaeldgraham** [comment]
So I have a fix put together, I'll get a PR submitted sometime this evening / tomorrow morning. Thank you very much for bringing this forward!

**Comment by smkhalsa** [comment]
Awesome, thank you!

**Comment by smkhalsa** [comment]
@michaeldgraham any update on this?

**Comment by michaeldgraham** [comment]
I had too many family obligations arise today, with the holiday season and such. I have a long drive ahead of me, but I'll hopefully be sitting down to get the fix in later this evening :)
