### ISSUE TITLE
Enum types not added to orderBy

### ISSUE THREAD

**Issue by GeoffThorpeFT** [neo4j-graphql/neo4j-graphql-js#168]
String and Boolean fields are added to the _xxxx_Ordering field but enums are not.
Is there a workaround?
We would like to sort by the contents of an enum field which contains a status.
Thanks.

**Comment by johnymontana** [comment]
The fix for this should be available now in v2.3.0. Please test and let us know if it works for you

**Comment by johnymontana** [comment]
Closing as the fix should be in #188 

Please reopen if this doesn't address your use case.
