### ISSUE TITLE
How to stop logging? 😔

### ISSUE THREAD

**Issue by appinteractive** [neo4j-graphql/neo4j-graphql-js#169]
How is it possible to disable the logging of cypher queries? I know what @johnymontana suggested in #52 but thats only possible in overwritten resolvers. 

But how to disable it completely? We need that for production and we CAN NOT LEAVE LOGGIN ON. 

I event tried to overwrite the logger in makeExecutableSchema but it does not have any effect of cause. 

PLEASE HELP! 😔

**Comment by michaeldgraham** [comment]
I'll take a look at this today

**Comment by johnymontana** [comment]
@appinteractive Now available in v2.2.0 is a `debug` option in the config object passed to `augmentSchema` and `makeAugmentedSchema`. For example:

```
const augmentedSchema = makeAugmentedSchema({
  typeDefs,
  config: {
    debug: false
  }
});
```

Could you give it a try?

I haven't added to docs yet, but will include it.

**Comment by appinteractive** [comment]
@johnymontana sadly its not working:
<img width="352" alt="grafik" src="https://user-images.githubusercontent.com/432828/50896909-da86b300-140a-11e9-8bff-93491f6ceca9.png">
<img width="666" alt="grafik" src="https://user-images.githubusercontent.com/432828/50896921-e2465780-140a-11e9-8351-7dd7180e00bb.png">

**Comment by appinteractive** [comment]
But WAIT: without the `config: {` it does work!
<img width="414" alt="grafik" src="https://user-images.githubusercontent.com/432828/50897116-74e6f680-140b-11e9-9bc0-eef4ea1c49f7.png">

**Comment by DomVinyard** [comment]
This does not work for me with or without the config
