### ISSUE TITLE
Unable to retrieve sub-field of a type, when queried via Query.<function>

### ISSUE THREAD

**Issue by u-phoria** [neo4j-graphql/neo4j-graphql-js#199]
Say we have a simple graph representing how people are mapped to teams, with ability to search teams by name:

```
type Person {
    id: String
    name: String
}

type  Team {
    id: String
    name: String
    members: [Person]   @cypher(statement: 
        "MATCH (this)<-[:BELONGS_TO]-(:TeamMembership)<-[:BELONGS_TO]-(p:Person) RETURN p”
    )
}

# Search function
type Query {
    teams(name_contains: String): [Team]
}
```

The following query works as expected, returning team members:

```
Team(name: "Product") {
    name
    members {
      name
    }
}
```

However this query

```
teams(name_contains: “Product“) {
    name
    members {
      name
    }
}
```
Produces the error

`Resolve function for \"Team.members\" returned undefined`

The lookup behind the `teams` query performs a basic Cypher query to look up Team nodes via a regex match. It returns records that are a superset (more properties) of those returned by the `Team` query that Is auto-generated by neo4j-graphql-js.

Any pointers on how this could be made to work, or anything I’m missing, much appreciated.

**Comment by johnymontana** [comment]
How do you implement the resolver for `teams`?

You could try adding the Cypher query as a `@cypher` schema directive. For example:

```
type Query {
    teams(name_contains: String): [Team] @cypher(statement: """
       MATCH (t:Team) WHERE t.name CONTAINS $name_contains // or replace use of CONTAINS with your regex
       RETURN t
    """)
}
```

**Comment by johnymontana** [comment]
Please re-open if the `@cypher` directive suggestion above does not address your use case.
