### ISSUE TITLE
Cannot generate multi-type relationships

### ISSUE THREAD

**Issue by MuddyBootsCode** [neo4j-graphql/neo4j-graphql-js#201]
```
type Created @relation(name: "CREATED_BY"){
  from: User
  to: Tract, Well, SWD, Operator
  date: Date
}
```

It's not currently possible to designate a relationship to multiple node types in a manner like that shown above.

**Comment by emregency** [comment]
@MuddyBootsCode I think that is typically a `union` type. 

Some exemples below:
https://www.apollographql.com/docs/apollo-server/features/unions-interfaces.html

**Comment by hataraxy** [comment]
I've tested union in order to make the relationship mutations working but it was KO.
#130 Feature Request: Union type support 
Also if fixed, this may answer your needs too :
 #182 [Question/Suggestion] Autogeneration of Mutations for relations to Interface types

**Comment by MuddyBootsCode** [comment]
I've ended up going the interface route. 
```
interface Alert {
    id: ID!
    title: String
    text: String
}

type LeaseAlert implements Alert {
    id: ID!
    title: String
    text: String
    lease: Lease @relation(name: "ALERT", direction: "OUT")
}

type TractAlert implements Alert {
    id: ID!
    title: String
    text: String
    tract: Tract @relation(name: "ALERT", direction: "OUT")
}
```
It's working so far but it'd be nice to have something less verbose.

**Comment by benjamin-rood** [comment]
Interface isn't a fit for relationships between types that don't share mostly identical fields.

**Comment by optimuspaul** [comment]
Also no solution that supports edges with properties

`The positions field on the Device node type uses the Position relationship type but Position comes from Positionable and goes to CoordinateSpace`

`Positionable` is an interface that `Device` implements.  `Position` is a relation that has properties and needs properties.
