### ISSUE TITLE
Removing console.log

### ISSUE THREAD

**Issue by dicearr** [neo4j-graphql/neo4j-graphql-js#21]
Is [this](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/src/index.js#L23) `console.log` necessary? Can I create a PR for removing it?

**Comment by johnymontana** [comment]
This was resolved by #25 being merged. By default the generated query is not logged, but you can optionally pass a param to log the generated query:

```
# 5th argument is the debug flag
neo4jgraphql(object, params, context, resolveInfo, true) 
```

This is available as of the v0.1.9 release on NPM. 

NOTE: we will probably change the signature for `neo4jgraphql` at some point to take a single object argument
