### ISSUE TITLE
Provide mechanism / attach Directives to 'auto generated mutations'

### ISSUE THREAD

**Issue by memolipd** [neo4j-graphql/neo4j-graphql-js#212]
Right now, we can use custom directives to specify auth/roles for querying objects or field definitions, but since the mutations are created automatically by the library, we don't have access to put custom directives on the mutations.

As a result, we can easily limit access to querying a neo4j db via custom directives, but by default all Create/Update operations are auto generated and therefore public.

I think best approach would be to integrate auth directives directly into the lib as I imagine most will be implementing it - surfacing a function to check for auth, given the context and returning allow/disallow.

A more simplified approach might be to apply the object level directives to the auto generated mutations

This way, the same logic could be pulled through to the querys and create/update mutations.

**Comment by johnymontana** [comment]
This has been implemented for the `isAuthenticated`, `hasRole` and `hasScope` authorization directives. See the [docs here](https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization.html#configuring-schema-directives)

Please reopen if this does not address your use case.
