### ISSUE TITLE
Issue: Relationship mutation wrong return when only "to" fields are requested

### ISSUE THREAD

**Issue by emregency** [neo4j-graphql/neo4j-graphql-js#218]
If I mutate an `add` relationship and request to `return` only `to` fields, I am getting a wrong `return`. If I request both `from` and `to` fields on `return`, it works.

Has anybody encountered a similar issue?

Thanks.

**Comment by michaeldgraham** [comment]
I haven't seen this before, I'll certainly check it out -- could you share an example of your schema and the mutation?

**Comment by emregency** [comment]
Maybe I am doing something wrong. Below the examples:
![doesnt_work1](https://user-images.githubusercontent.com/10894960/54717772-4303b600-4b59-11e9-8962-9915aa0be589.PNG)
![doesnt_work2](https://user-images.githubusercontent.com/10894960/54717773-439c4c80-4b59-11e9-9b59-d99577485d6c.PNG)
![works](https://user-images.githubusercontent.com/10894960/54717807-544cc280-4b59-11e9-9865-596582247bed.PNG)

**Comment by robinelvin** [comment]
I am getting a similar problem. It looks to be generating incorrect Cypher. Here's what it correctly generates when specifying `from` and `to` in the mutation response:

```
MATCH (`user_from`:`User` {emailAddress: $from.emailAddress})
MATCH (`organisation_to`:`Organisation` {id: $to.id})
CREATE (`user_from`)-[`organisationmembership_relation`:`OrganisationMembership` {invitedAt: datetime($data.invitedAt),identifier:$data.identifier,stage:$data.stage}]->(`organisation_to`)
          RETURN `organisationmembership_relation` { invitedAt: { formatted: toString(`organisationmembership_relation`.invitedAt) },acceptedAt: { formatted: toString(`organisationmembership_relation`.acceptedAt) }, .stage , .identifier ,from: `user_from` { .emailAddress } ,to: `organisation_to` { .id , .name ,rolesAvailable: [(`organisation_to`)-[:`AVAILABLE_ROLE`]->(`organisation_to_rolesAvailable`:`Role`) | organisation_to_rolesAvailable { .name , .realm , .realmUUID }] }  } AS `_AddUserOrganisationMembershipPayload`;
```

Here's what it generates when only specifying `to` in the mutation response:

```
MATCH (`user_from`:`User` {emailAddress: $from.emailAddress})
MATCH (`organisation_to`:`Organisation` {id: $to.id})
CREATE (`user_from`)-[`organisationmembership_relation`:`OrganisationMembership` {invitedAt: datetime($data.invitedAt),identifier:$data.identifier,stage:$data.stage}]->(`organisation_to`)
          RETURN `organisationmembership_relation` { invitedAt: { formatted: toString(`organisationmembership_relation`.invitedAt) },acceptedAt: { formatted: toString(`organisationmembership_relation`.acceptedAt) }, .stage , .identifier ,to: `user_from` { .id , .name ,rolesAvailable: [(`organisation_to`)-[:`AVAILABLE_ROLE`]->(`organisation_to_rolesAvailable`:`Role`) | organisation_to_rolesAvailable { .name , .realm , .realmUUID }] }  } AS `_AddUserOrganisationMembershipPayload`;
```

As you can see, it is using the wrong node for the `to` object - it is trying to extract the fields from the `user_from` node.
