### ISSUE TITLE
Query type cypher directive not recognized

### ISSUE THREAD

**Issue by johnymontana** [neo4j-graphql/neo4j-graphql-js#22]
Query type:

```
type Query {
    GenresBySubstring(substring: String): [Genre] @cypher(statement: "MATCH (g:Genre) WHERE toLower(g.name) CONTAINS toLower($substring) RETURN g")
}
```

GraphQL query:
```
{
  GenresBySubstring(substring: "Action") {
    name
    highestRatedMovie {
      title
    }
  }
}
```

generated Cypher query: 

```
MATCH (genre:Genre {substring:"Action"}) 
RETURN genre { .name ,
	highestRatedMovie: head([ x IN apoc.cypher.runFirstColumn("MATCH (m:Movie)-[:IN_GENRE]->(this) RETURN m ORDER BY m.imdbRating DESC LIMIT 1", {this: genre}, true) | x { .title }]) } AS genre SKIP 0
```

Expected Cypher query from cypher directive on `GenresBySubstring` instead of default MATCH

**Comment by bebbi** [comment]
For me cypher directives appear already seem removed in in makeExecutableSchema call, only the defaults (skip, include, deprecated) are there.

Do we need to declare the cypher directive when [creating the schema](https://github.com/graphql/graphql-js/blob/f995c1f92e94d9c451104b6a0db8034165ef8640/src/type/schema.js#L67)?
