### ISSUE TITLE
(Minor) ava needs an upgrade

### ISSUE THREAD

**Issue by moxious** [neo4j-graphql/neo4j-graphql-js#224]
Version of ava being used is 0.25, which is very far out of date of latest https://github.com/avajs/ava/releases/tag/v1.4.1 as of this issue.

The latest has some nifty assert things which would be nice to have in unit testing.  Upgrading doesn't seem super-straightforward because of some babel translation issues when I tried upgrading.  When possible, something to check into.

**Comment by johnymontana** [comment]
We're now using version ^2.2.0 of ava
