### ISSUE TITLE
relation & input type

### ISSUE THREAD

**Issue by francescovenica** [neo4j-graphql/neo4j-graphql-js#226]
I'm not sure if this is a bug, but if I won't use relation on my schema I should be able to use words like from/to as I want...actually if I add from/to to an input type I got an error `Directive "relation" may not be used on INPUT_OBJECT.`
what do you think?

**Comment by michaeldgraham** [comment]
Uh oh, this looks like a bug with the identification of relationship types during the schema augmentation process. I'll include a fix to prevent this in an upcoming PR, sorry about that!

**Comment by francescovenica** [comment]
no worries! I just started with this amazing db, is not a big problem and I found it randomly, so is not a problem at all...

**Comment by johnymontana** [comment]
Fixed in #228, please reopen if you are still seeing this behavior.
