### ISSUE TITLE
Request for info: Does this project support authenticated/protected nodes, properties, and relationships?

### ISSUE THREAD

**Issue by Joshfindit** [neo4j-graphql/neo4j-graphql-js#238]
Apologies for raising an issue for this, I could not find a discussion or community link in the README, on Github, or on the docs (including the [resources](https://grandstack.io/docs/neo4j-graphql-js.html#resources) section)

#### The question is
 Given whatever authentication method/schema/setup required:

**Can we store nodes, properties, and relationships that can each be protected at a per-user or per-group level?**

#### Things like

`Post` has `date_modified`, `date_submitted`, `Author` (as relationship), `Coworker` (As relationship to another `Author`), `Manager` (boss to `Author`s), and `Location` (as relationship)

(aka `(editorial:Post)<-[AUTHORED]-(john:Author)<-[IS_MANAGER]-(jessica:Manager)-[MEMBER_OF]->(managers:Group)`, `(jessica)-[AT_LOCATION]-(head_office:Location)`, `(john)-[IS_COWORKER]-(jeffrey:Author)`, and so-on)

- Restrict the public from pulling any "IS_MANAGER" relationships
- Restrict access to `date_submitted` to only Authors and Managers
- Allow public to list Managers, but not their subordinates (Say, for an "About Us" page)
- Restrict returning _any_ `Location` node to Managers only

If not currently; is this in the future plans?

**Comment by smkhalsa** [comment]
You can use middleware such as [graphql-shield](https://github.com/maticzav/graphql-shield). I've found that solution to work quite well as you can limit access based on arbitrary rules.

**Comment by iPwnPancakes** [comment]
Currently using [graphql-auth-directives](https://github.com/graphql-community/graphql-directive-auth) and auth0 to handle authorization and authentication in our product. Its served us quite well!

**Comment by johnymontana** [comment]
Please see the [GraphQL Authorization section in the docs](https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization.html) for the various authorization features supported.
