### ISSUE TITLE
Feature request: makeAugmentedSchema and Apollo's buildFederatedSchema integration support

### ISSUE THREAD

**Issue by emregency** [neo4j-graphql/neo4j-graphql-js#260]
Typically,

Types may have different attributes that are requiring other dB/service access than neo4j i.e. profile photos for User where the link is stored in neo4j db and the image itself somewhere else ([a recommended practice by neo4j](https://neo4j.com/blog/dark-side-neo4j-worst-practices/)). In such cases, stitching schemas to different services is required but is quite painful.

The new release of [Apollo Federation](https://blog.apollographql.com/apollo-federation-f260cf525d21) provides a very convenient way to manage these multi service API design. 

However,

The implementation requires the developer to _augment the schema_ with a new method called `buildFederatedSchema` where new directives for managing easily the interdependence among schemas are introduced :

```
const server = new ApolloServer({
  schema: buildFederatedSchema([{ typeDefs, resolvers }])
});
```
as illustrated [here](https://www.apollographql.com/docs/apollo-server/federation/implementing/#defining-a-federated-service). 

Is it possible to concatenate or provide an elegant way of enabling `makeAugmentedSchema` and `buildFederatedSchema` ?

**Comment by johnymontana** [comment]
Yes, this is definitely something we'll need to look into. I have it on my list to research.

**Comment by Pruxis** [comment]
If you don't want the complete shebang of having automaticly generated Mutations & Queries, then I think exposing the directives should be good enough.

**Comment by Pruxis** [comment]
Hey @emregency I got this working but without the generated queries and mutations (which is our desired use case)

You can just import the directives like this

``` javascript
import { cypherDirective, relationDirective } from 'neo4j-graphql-js/dist/utils';

const server = new ApolloServer({
  schema,
  schemaDirectives: [{ cypher: cypherDirective, relation: relationDirective }],
  context: (): Context => ({ driver }),
  playground: true,
  introspection: true,
});

// Sample resolvers
import { neo4jgraphql } from 'neo4j-graphql-js';
const resolvers = {
  Query: { test: neo4jgraphql }
}
```

**Comment by emregency** [comment]
Hey,

Thanks a lot for your contributions to the library. I use the mutations as they are convenient for the development phase. I prefer to have all of them as we build the front end. For sure, after certain point I would only use the directives. 

Cheers!

**Comment by emregency** [comment]
Hey!

I saved this in a corner. Thanks a lot!

**Comment by Pruxis** [comment]
@emregency also check https://github.com/neo4j-graphql/neo4j-graphql-js/pull/283

**Comment by wheresrhys** [comment]
I'm interested what the clashes are between makeAugmentedSchema and buildFederatedSchema are? e.g. does it clash with one of mutations, filters, ordering specifically, or is it to do with soething more fundamental in how makeAugmatedSchema processes the schema

**Comment by maieulChevalier** [comment]
Hi @Pruxis, thanks for posting your solution. I tried it but couldn't make it work with buildFederatedSchema. I keep getting these errors:
`errorsGraphQLSchemaValidationError: Unknown directive "cypher".
errorsGraphQLSchemaValidationError: Unknown directive "relation".` 

But it works perfectly fine if I remove all the @cypher and @relation directives.

Here's my code:

````
const server = new ApolloServer({
  schema: buildFederatedSchema([{
    typeDefs,
    resolvers,
  }]),
  schemaDirectives: { cypher: cypherDirective, relation: relationDirective },
  context: ({req}) => { 
    return {
      headers: req.headers,
      driver }},
  introspection: true,
  playground: true,
});`
```

Any help is more than welcome :)

**Comment by maieulChevalier** [comment]
Okay, the problem was coming from the schema itself. Just adding the directives that I found in the generated schema of makeAugmentedSchema to the schema and it works.

```
directive @cypher(statement: String) on FIELD_DEFINITION
directive @relation(
  name: String
  direction: _RelationDirections
  from: String
  to: String
) on FIELD_DEFINITION | OBJECT
directive @additionalLabels(labels: [String]) on OBJECT
directive @MutationMeta(
  relationship: String
  from: String
  to: String
) on FIELD_DEFINITION
directive @neo4j_ignore on FIELD_DEFINITION
directive @isAuthenticated on OBJECT | FIELD_DEFINITION
directive @hasRole(roles: [Role]) on OBJECT | FIELD_DEFINITION

enum _RelationDirections {
  IN
  OUT
}
```

**Comment by bwalsh** [comment]
Hell all.   Newbie question.  Just started experimenting with grandstack + apollo federation.  Is there a canonical example on how this should work?

**Comment by davidLeonardi** [comment]
I second @bwalsh 's request. Could someone please point towards documentation on how this can be used? It's quite unclear at the moment.

My usecase is that i need federation because one graphql service handles some domain business logic, and the neo4j data is handled by a separate service.

Thanks :)

**Comment by agnewp** [comment]
i would love to be able to use the augmented schema with Apollo federation. without federation support, i can only (barely/awkwardly) use your directives. :(

**Comment by michaeldgraham** [comment]
Hi everyone! We recently updated with support for using Apollo Federation & Gateway. You can check out a guide added to the documentation [here](https://grandstack.io/docs/apollo-federation-gateway-with-neo4j.html). I didn't notice to reference this issue in the recent PR, but it is now. :)

**Comment by bwalsh** [comment]
Thanks very much.  Looking forward to trying this soon.
