### ISSUE TITLE
Feature request: Enum Support

### ISSUE THREAD

**Issue by sys13** [neo4j-graphql/neo4j-graphql-js#28]
Would love to have enums supported. For now, I'm resorting to just using String types and enforcing enum values only at the front-end :cry:

**Comment by johnymontana** [comment]
Support for enums was just added in https://github.com/neo4j-graphql/neo4j-graphql-js/commit/0944e0644914fc97d50e7109b810e1cc246df628 and is available on NPM v0.1.13

Please test if it works for you. Thanks!
