### ISSUE TITLE
How to filter on computed properties 

### ISSUE THREAD

**Issue by danielrearden** [neo4j-graphql/neo4j-graphql-js#287]
Assume we have the following schema:

```
type Foo {
  id: ID!
  bars: [Bar!]! @relation(name: "INSIDE_OF", direction:"IN")
}

type Bar {
  id: ID!
  start: DateTime!
  foo: Foo! @relation(name: "INSIDE_OF", direction:"OUT")
  current: Boolean! @cypher(statement: "RETURN this.start < datetime()") 
}
```

We have a calculated field named `current` that returns whether the node in question has a `start` field that's less than the current timestamp. Querying this sort of field works fine. However, not surprisingly, the generated filter input for the Bar type does not include this property.

So if I wanted to query only Bars that are current, I would have to use the `@cypher` directive combined with my own input type(s). Moreover, in order to fetch Foos with only current Bars, I would likewise have to swap the `@relation` directive for a `@cypher` directive with my own filter input type. And I'd have to do that for each type Bar is related to.

I'm wondering if there's any easier approaches to handling this sort of scenario. If not, how feasible would it be for the library to add fields marked with a @cypher directive to the generated filter input type (maybe based on some optional directive argument)?

**Comment by hnrklssn** [comment]
Why was this closed? Filtering on computed properties is a very relevant use case for me. I've heard concerns voiced in other issues that it might introduce too much performance penalties, but filtering on computed boolean properties feels like a good compromise, to start with. They're pretty easy to manually add by the programmer if they decide that the penalty is small enough to be worth it, and shouldn't be too hard to add into the filter generation either.
