### ISSUE TITLE
Auto-commit transactions vs transaction functions

### ISSUE THREAD

**Issue by meddyrainzo** [neo4j-graphql/neo4j-graphql-js#29]
This is more of a question than an issue/bug

Reading the documentation of the neo4j javascript driver, it warns against using auto-commit transactions in production. It advices to use transactional-functions wherever possible.

Is there any reason why auto-commit transactions were chosen over transaction functions for this project?

**Comment by johnymontana** [comment]
Fixed in 1fbc747ec090e538f61f192f77749eb7f1aa878a
