### ISSUE TITLE
Pagination via edges and the Connection Model

### ISSUE THREAD

**Issue by tmscer** [neo4j-graphql/neo4j-graphql-js#292]
Is there a simple way to query for related objects via Connection Model as described here https://graphql.org/learn/pagination/#end-of-list-counts-and-connections? I failed to find such a way in documentation and implementing it via cypher seems difficult if not impossible and repetitive which defeats the whole purpose of this library. 

Is this a feature that may be introduced in the future?

**Comment by Joshfindit** [comment]
@tmscer Pagination is always going to be challenging in any graph database.
Neo4j specifically mentions that nodes may be returned in any order during any query, and deciding on a sort first is going to reduce performance + introduce issues (such as missing items or showing duplicates while flipping between pages)
