### ISSUE TITLE
Interfaces not working with @Cypher 

### ISSUE THREAD

**Issue by michal-trnka** [neo4j-graphql/neo4j-graphql-js#294]
Interfaces do not work with directive @cypher. This graphql definition is not working. 

```
interface Location {
  name: String!
}

type Company {
  locations: [Location!] !@cypher(
    statement: "MATCH whatever")
}
```

I tried to make cypher statement to return `FRAGMENT_TYPE` using this query:
```
MATCH (this)-[:SMTH]-(location) WHERE ... RETURN location{ .*, FRAGMENT_TYPE:labels(location)[0]}
```
however, if the @cypher statement is used, this piece is not carried out to the final return value.

**Comment by Carnewal** [comment]
#296 fixes this

**Comment by slowercz** [comment]
@johnymontana not working for me :(

It looks like it was added to `customQuery`and `customMutation` but it was not added to method `customCypherFields`

My type definition:
```
type TestType {
  uuid: ID!
  locations: [Location!]! @cypher(
    statement: """
    MATCH (this)-[:TARGETS]->(l)
    WHERE l:City OR l:AdministrativeLocation1 OR l:AdministrativeLocation2 OR l:Country OR l:Region
    return l
    """)
}
```

and the resulting query without FRAGMENT_TYPE
```
MATCH (`testType`:`TestType` {uuid:$uuid}) RETURN `testType` { .uuid ,locations: [ testType_locations IN apoc.cypher.runFirstColumn("MATCH (this)-[:TARGETS]->(l)
WHERE l:City OR l:AdministrativeLocation1 OR l:AdministrativeLocation2 OR l:Country OR l:Region
return l", {this: testType}, true) | testType_locations { .name }] } AS `testType`

```

**Comment by Carnewal** [comment]
Should be there @slowercz , see commit -- https://github.com/neo4j-graphql/neo4j-graphql-js/pull/296/commits/0d5170a54113c4da7b6c052895b87753de7ae785

**Comment by slowercz** [comment]
@Carnewal 
Sorry, my bad, did not see that for some reason.

`fieldType.ofType.astNode.kind` is undefined.
`FieldType.ofType` is `[Location!]!`, `FieldType.ofType.ofType` is `Location!` and finaly `FieldType.ofType.ofType.ofType` is `Location` and I can call `FieldType.ofType.ofType.ofType.astNode.kind`
