### ISSUE TITLE
Sub-queries on Cypher-generated properties

### ISSUE THREAD

**Issue by judas-christ** [neo4j-graphql/neo4j-graphql-js#30]
So this is part bug report, part question about how to do this right. Let's say I have a property that uses a Cypher statement to get nodes that are indirectly related:

```graphql
type Movie {
  actorMovies: [Movie] @cypher(statement: "MATCH (this)-[:ACTED_IN*2]-(other:Movie) RETURN other")
}
```
and I make a query like this:
```graphql
{
  Movie(title: "Top Gun") {
    actorMovies {
      title
      actor { name }
  }
}
```
The Cypher query generated looks like this:
```cypher
MATCH (movie:Movie {title:"Top Gun"}) RETURN movie {actorMovies: [ x IN apoc.cypher.runFirstColumn("MATCH (this)-[:ACTED_IN*2]-(other:Movie) WHERE this <> other RETURN other", {this: movie}, true) | x { .title ,actors: [(movie_actorMovies)<-[:ACTED_IN]-(movie_actorMovies_actors:Actor) | movie_actorMovies_actors { .name }] }] } AS movie SKIP 0
```

This query returns the actors for *all* movies on each movie. The bug occurs because the sub-query for actor names use `movie_actorMovies` as node name, but the code from the cypher statement uses `x`. So that's the bug. Is there a better, more "correct" way of achieving this?

**Comment by sys13** [comment]
I've been defining custom resolvers for fields that have @cypher on them.
If there's a way for the library to put my @cypher in a sub query that
would be even better.
