### ISSUE TITLE
DateTime not working with Interface

### ISSUE THREAD

**Issue by michal-trnka** [neo4j-graphql/neo4j-graphql-js#305]
DateTime type can not be used in interfaces.

This schema
```
interface MyInterface{
myDate: DateTime
}

type MyType implements MyInterface{
myDate: DateTime
}
```

Leads to:
`Error: Interface field MyInterface.myDate expects type DateTime but MyType.myDate is type _Neo4jDateTime.`

**Comment by smkhalsa** [comment]
As a temporary workaround, you can use replace `DateTime` with `_Neo4jDateTime` in both the interface and implementation, and it should work. You will also need to add `scalar _Neo4jDateTime` to your schema.

**Comment by johnymontana** [comment]
This has been fixed, but please reopen if you're still seeing this behavior.

Also, the docs for working with Interfaces is here: https://grandstack.io/docs/graphql-interface-union-types.html

**Comment by benjamin-rood** [comment]
@johnymontana So we can use `DateTime` now, rather than `_Neo4jDateTime`?
What was the commit / release that fixed this?
