### ISSUE TITLE
problems with union

### ISSUE THREAD

**Issue by francescovenica** [neo4j-graphql/neo4j-graphql-js#307]
Hello, 

I'm trying to set the 2 types for the same property based on the input, I mean, the property `reviewed` could be a `User` or a `Company` depending on the mutations sent....I'm trying to do this with the union like the one below

```
union Any = Company | User
type Review {
  uuid: ID!
  stars: Int
  text: String
  owner: User @relation(name: "REVIEWD", direction: "IN")
  reviewed: Any @relation(name: "HAS_REVIEW", direction: "IN")
}
```

but when I run it I get this error:
```
schemaType.getFields is not a function
```

any suggestions?

**Comment by francescovenica** [comment]
I've updated the plugin to last version and I don't get the error anymore but query is wrong as it try to search for the label `Any` instead of `User` or `Company`

**Comment by smkhalsa** [comment]
I also ran into this issue. 

```
union SearchResult =
    Album
  | Artist
  | FeaturedPlaylist
  | Song

type Query {
  Search(string: String!): [SearchResult!]!
    @cypher(
      statement: """
      CALL db.index.fulltext.queryNodes('names', $string) YIELD node, score
      RETURN node
      """
    )
}
```

when I run the following query
```
query {
  Search(string:"Seal") {
    __typename
  }
}
```

I get the same error as @francescovenica (i.e. `schemaType.getFields is not a function`). However, if I run the following:
```
query {
  Search(string:"Seal") {
    ...on Song {
      name
    }
  }
}
```
I get the following error:
```
Abstract type SearchResult must resolve to an Object type at runtime for field Query.Search with value { name: \"Seal\" }, received \"undefined\". Either the SearchResult type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.
```

Ultimately I refactored my code to use an `interface` instead of a `union` type and now everything is working properly (remember, a GraphQL type can implement multiple interfaces).

**Comment by benjamin-rood** [comment]
> Ultimately I refactored my code to use an `interface` instead of a `union` type and now everything is working properly (remember, a GraphQL type can implement multiple interfaces).

Interfaces have significant overheads, though, including unnecessary schema duplication, and using `interface` as a workaround for `union` means you often have to resort to bloated "catchall" interfaces and this produces a tendency to copypasta stuff.

`union` is part of the GraphQL spec. It must be implemented by this library.

**Comment by johnymontana** [comment]
Example use case from @benjamin-rood:


```
union AB = A | B
type Device {
  guid: ID!
  mac_address: MAC!
  allocatedTo: [A!] @relation(name: "ALLOCATED_TO", direction: "OUT")
  loadedBy: [AB!] @relation(name: "LOADED_BY", direction: "OUT")
  extraSettings: XML
}
```

![union_erd_example](https://user-images.githubusercontent.com/1222454/69448933-e6275380-0d16-11ea-81b6-ec41aaec201c.jpg)


> I've gotten around not having union support thus far by only including the relationship on the other side, i.e. forcing a reverse lookup from A and B  to find matching Device nodes, but in this case that's really not gonna fly 

> In fact, writing the relation manually in cypher will work fine, but it still can't be expressed defined properly in the schema without resorting to an interface.

**Comment by johnymontana** [comment]
Another example use case from @benjamin-rood (error handling):

> per this model: https://www.youtube.com/watch?v=A5-H6MtTvqk&feature=emb_title
Include "quasi-errors" in the schema (model them)

e.g. `union UserResult = User | Deleted | Unavailable`

given:

```
type User {
  id: ID!
  name: String
}
type Deleted {
  details: JSON!  # e.g. When deleted, etc
  user: User
}
type Unavailable {
  reason: String
}
We get a query type like so:
type Query {
  user(id: ID!): UserResult!
}
```

> Where Deleted, Unavailable are Error categories, which provides:

> * Ability to distinguish between expected states (within the model) and unexpected states (true system or network errors, outside the model)
> * Results which are customisable for each entity and recursive, and SIMPLE
> * Client decides what results it cares about, what results it can ignore
> * As a result "errors" don't cause failures in nested queries
> * Tune for desired output and verbosity
> * More accurately represent interactions with our system


See also: https://medium.com/@sachee/200-ok-error-handling-in-graphql-7ec869aec9bc

**Comment by johnymontana** [comment]
v2.13.0 adds improved handling of interface and union types based on multiple labels in Neo4j, please see the docs here for more info: https://grandstack.io/docs/graphql-interface-union-types.html
