### ISSUE TITLE
unit test example

### ISSUE THREAD

**Issue by francescovenica** [neo4j-graphql/neo4j-graphql-js#310]
I would like to add some test but I'm not sure how can I do that, I tried to do some research but I didn't find anything, do you have some example, or can you give some advice?

**Comment by johnymontana** [comment]
Hi @francescovenica - the typical test is comparing the generated Cypher for a given GraphQL request, and asserting it is what's expected. Here's an example: 

https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/test/unit/cypherTest.test.js#L13-L31

You can add more tests by following that example.
