### ISSUE TITLE
Is there a way to mark properties as external?

### ISSUE THREAD

**Issue by frankwanicka** [neo4j-graphql/neo4j-graphql-js#34]
We are doing schema stitching and I need a way to mark a property as "external", so it is ignored by neo4j-graphql-js when parsing. Is there anything implemented for that purpose yet?

**Comment by johnymontana** [comment]
Not currently. What exactly would you need to make that work? If we checked for a `@external` schema directive on a field and just ignored the field when generating the Cypher query, would that work?

**Comment by frankwanicka** [comment]
Yep. I have that approach working locally. I just wanted to make sure I wasn't missing something before creating a pull request.

**Comment by johnymontana** [comment]
Sure. Sounds good to me. Happy to review a PR for it. Sounds like something anyone doing schema stitching would find useful.

**Comment by johnymontana** [comment]
We've added a `@neo4jignore` directive, which when added will exclude the field from the augmentation process and the generated Cypher query.

Fixed by #183
