### ISSUE TITLE
"Expected parameter(s): derivedTypes"

### ISSUE THREAD

**Issue by emregency** [neo4j-graphql/neo4j-graphql-js#346]
After the `2.9.0` update, 

The inline fragments are breaking with the following error: 
`"Expected parameter(s): derivedTypes"`

I have my type resolver as follows: 
```  
OldCamera: {
    __isTypeOf(obj, _ctx, _resolveInfo) {
      return obj["FRAGMENT_TYPE"] || "OldCamera";
    }
  },
```

@flazoon  do you have any clues about that :)

**Comment by johnymontana** [comment]
@emregency can you share the type definitions for `OldCamera` and related interface types? I'm assuming you are defining both the interface and the implementing types?

**Comment by flazoon** [comment]
@emergency, could you please also share the query that leads to the error in addition to what other details @johnymontana requested?

**Comment by emregency** [comment]
Hey guys,

All my apologize for the delay. I needed to be absent from work for a week for some family issues, and lately we were busy deploying a new version for a customer. I am just having time to investigate the issue. 

The issue happens when I query a field with a custom cypher statement that returns an interface. As far as I checked there is no such use case in the `testSchema`. An example could be:

```
extend type Movie {
 bestPerson: Person @cypher( statement: "MATCH (u:Person)--(this) RETURN u ORDER BY u.name DESC LIMIT 1")
}
```

In my case, the query is:
```
Project {
latestProjectElement: ProjectElement
	@cypher(
		statement: "MATCH (u:ProjectElement)-[:COMPOSES]->(this) RETURN u ORDER BY u.capturedOn DESC LIMIT 1"
	)
}
```
The interface is:
```
interface ProjectElement {
id: ID!
description: String!
}
```
And the implemented interface is:
```
type Information implements ProjectElement {
id: ID!
description: String!
...
}
```
And the error is: 
```
Abstract type ProjectElement must resolve to an Object type at runtime for field Project.latestProjectElement with value { description: "abc", capturedOn: { formatted: "2019-12-04T10:16:03.312Z" }, id: "2cbc7400-3290-4429-b1fe-6671b1040198" }, received "undefined". Either the ProjectElement type should provide a "resolveType" function or each possible type should provide an "isTypeOf" function.
```

All other interface queries resolve perfectly. The problem is only with the field.
