### ISSUE TITLE
Interfaces with no scalar fields generate invalid schemas.

### ISSUE THREAD

**Issue by mchong-teal** [neo4j-graphql/neo4j-graphql-js#349]
Just attempting to integrate neo4j-graphql-js into existing graphql/node/neo4j stack.  Seems cool but I can't get it to build the schema.  At the moment I'm getting the following errors for each of my interface types:

```Error: Enum type _[Interface]Ordering must define one or more values.```

(replacing [Interface] with the type name.

Not sure what I'm doing wrong..

**Comment by mchong-teal** [comment]
I think I figured it out.  None of those interfaces have a field with a scalar type (only object and array of objects), so it creates empty auto-generated enums..

**Comment by mchong-teal** [comment]
Temporary work around to add a dummy scalar field..

**Comment by DerMika** [comment]
Came here after hitting the same issue with version 1.9.3.

**Comment by johnymontana** [comment]
This should be fixed in the latest version v2.11.3 by PR #365 , please reopen if you're still seeing issues
