### ISSUE TITLE
issue on fragments after upgrade from 2.11.5 to 2.12.1

### ISSUE THREAD

**Issue by emregency** [neo4j-graphql/neo4j-graphql-js#387]
After the recent upgrade I started to get the following errors. I couldn't dig into it yet but will post if I catch something.

```
"message": "Cannot read property 'name' of undefined",
[...]
"extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'name' of undefined",
            "    at buildCypherSelection (\\node_modules\\neo4j-graphql-js\\dist\\selections.js:137:33)",
            "    at recurse (\\node_modules\\neo4j-graphql-js\\dist\\selections.js:87:33)",
            "    at buildCypherSelection (\\node_modules\\neo4j-graphql-js\\dist\\selections.js:211:22)",
            "    at recurse (\\node_modules\\neo4j-graphql-js\\dist\\selections.js:87:33)",
            "    at buildCypherSelection (\\node_modules\\neo4j-graphql-js\\dist\\selections.js:188:12)",
            "    at customQuery (\\node_modules\\neo4j-graphql-js\\dist\\translate.js:585:68)",
            "    at translateQuery (\\node_modules\\neo4j-graphql-js\\dist\\translate.js:528:12)",
            "    at cypherQuery (\\node_modules\\neo4j-graphql-js\\dist\\index.js:175:40)",
            "    at _callee$ (\\node_modules\\neo4j-graphql-js\\dist\\index.js:83:31)",
            "    at tryCatch (\\node_modules\\regenerator-runtime\\runtime.js:45:40)"
          ]
        }
      }
```

**Comment by benjamin-rood** [comment]
We've encountered the same thing. It's not present on complete queries without fragments, but the identical effective query composed of fragments fails with exactly this error. It was happening to me all last week and I kept thinking it was something I was breaking in my code by doing something fancy...!

It's appears to have been introduced from the upgraded neo4j driver dependency to v4.0.* to support v4.0 of Neo4j proper.

@johnymontana This is better labeled as _breaking_ support for fragments.

**Comment by mattwr18** [comment]
We are also getting this when trying to upgrade to `neo4j 4` and using `neo4j-graphql-js@2.12.1`
We are on `2.11.5` in production with `neo4j 3.5` and have not had an issue.

**Comment by johnymontana** [comment]
Are folks still having this problem with recent versions?

Regarding the difference with the same query working in GraphiQL but not Apollo Client, I know Apollo Client adds `__typename` to support their cache, if adding `__typename` to the selection set triggers the error that could be a possible explanation.

**Comment by johnymontana** [comment]
Closing this now. If you see this error again please re-open or create a new issue.
