### ISSUE TITLE
Authorization schema directives are ignored on extended types

### ISSUE THREAD

**Issue by simon-bigsofa** [neo4j-graphql/neo4j-graphql-js#389]
Adding a schema directive to a normal type will properly authorise access to the type based on the directive but the same declaration on an extended type simply ignores the directive altogether.

Correctly authorised:
`type Media @hasRole(roles: [admin])`

Does nothing:
 `extend type Media @hasRole(roles: [admin])`

**Comment by simon-bigsofa** [comment]
This is actually an issue with `graphql-tools`

See https://github.com/apollographql/graphql-tools/issues/1296 for details. Solved by switching to `graphql-tools-fork` which has a fix.

**Comment by johnymontana** [comment]
Per the GraphQL spec directives provided on the extension can't already be used on the original type, so you may have been running into that. From the spec [here](http://spec.graphql.org/June2018/#sec-Object-Extensions):

> Any directives provided must not already apply to the original Object type.

So in this case this would prevent the type extension from overriding authorization rules that had been defined on the original type.
