### ISSUE TITLE
Error with query with inline fragment in version 2.12.1

### ISSUE THREAD

**Issue by DavidCarneros** [neo4j-graphql/neo4j-graphql-js#393]
Error with query with inline fragment in version 2.12.1
​
The error occurs with all queries that are made with an inline fragment implemented in the scheme through an interface that is inherited by the other types. 
​
For example the query
```graphql
query getHeroes { 
  Hero (id:5) { 
    id  
    heroType {
      ... on Droid {
        name
      }
    }
  }
}
```
It returns nothing in the heroType field. 
​
The field type in Hero is declared in the graphql scheme as follows: 
```graphql
heroType: [HeroesType] @relation(name:"heroType", direction: "OUT")
```
​
And the type that can be requested are of the type Droid, Human and Stormtrooper that implement the HeroesType interface.
​
​
The problem is that when the query is generated in cypher:
​
```cypher
MATCH (`hero`:`Hero` {id:5}) 
RETURN `hero` { .id ,heroType: [(`hero`)-[:`heroType`]->(`hero_heroType`:`HeroesType`) 
| hero_heroType {FRAGMENT_TYPE: head( [ label IN labels(hero_heroType)
 WHERE label IN [ 'Droid', 'Stormtrooper', 'Human' ] ] ),  .id }] } AS `hero`
```
​
It adds to the `hero_heroType` node the` HeroesType` label that does not exist in the db of neo4j because it is the name of the interface that implements those resources.
​
The query graphql does work in version 2.7.2.
​
Thanks in advance.

**Comment by johnymontana** [comment]
Could you try this with the latest release v2.13.0? This version includes significant updates to the translation logic for interfaces and inline fragment.

**Comment by johnymontana** [comment]
Closing this as this should be fixed now, but please reopen if you're seeing issues still.

Also see the docs for working with multiple labels with Interfaces: https://grandstack.io/docs/graphql-interface-union-types.html
