### ISSUE TITLE
Return null for the fields not array

### ISSUE THREAD

**Issue by cricrio** [neo4j-graphql/neo4j-graphql-js#4]
For example when we are querying with this schema neo4jgraphql return a post where owner is in an array and not an object. Then Apollo server sends null for each property of User. 
```
type Post{
  name : String
  owner : User  @relation(name: "WRITE", direction:"IN")
}
```

**Comment by johnymontana** [comment]
Thanks @cricrio for reporting!

I've pushed a fix for this (I think!) in d6210aa7522419c50654ac3733e56d71e94839ec and published to npm as v0.1.5

Could you try again with that version?

**Comment by cricrio** [comment]
It's working !

**Comment by johnymontana** [comment]
Great! Keep the bug reports coming - it’s very helpful :-)
