### ISSUE TITLE
Mutation Error - must have a selection of subfields

### ISSUE THREAD

**Issue by SujaYuga** [neo4j-graphql/neo4j-graphql-js#404]
Hi,

I am using below version of neo4j-graphql-js. When I try to access (both query and mutation) a simple node with 2 properties and no relations, I am able to query the node but when try to access the default mutation methods provided by neo4j-graphql-js, I get the error of "must have a selection of subfields..". Below are the error details from GraphQL Playground. Please help and advise what I am doing wrong in my code or GraphQL input format.

**Package versions**
 "apollo-server": "^2.9.4",
    "esm": "^3.2.25",
    "neo4j-driver": "^1.7.6",
    "neo4j-graphql-js": "^2.7.2"

**NodeJS Code - typeDefs**
const typeDefs = `
type User {
    email: String
    uname: String
}
`;

**Graphql Playground - Input**
mutation{
  CreateUser(email: "test1" uname: "test2")
}

**Graphql Playground - Error**
{
  "error": {
    "errors": [
      {
        "message": "Field \"CreateUser\" of type \"User\" must have a selection of subfields. Did you mean \"CreateUser { ... }\"?",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Field \"CreateUser\" of type \"User\" must have a selection of subfields. Did you mean \"CreateUser { ... }\"?",

**Comment by johnymontana** [comment]
Hi @SujaYuga - the `CreateUser` mutation returns a `User` object type. Since this is an object type (and not a scalar) the GraphQL query must specify one or more fields of the type to be returned. Try something like this:

```
mutation{
  CreateUser(email: "test1" uname: "test2") {
    email
    uname
  }
}
```

**Comment by SujaYuga** [comment]
Awesome! That worked. Thanks a bunch!
