### ISSUE TITLE
Nested Filters do not work as expected for Interface types

### ISSUE THREAD

**Issue by Phylodome** [neo4j-graphql/neo4j-graphql-js#409]
**Version**: 2.13.0

**Problem**: Nested filters no longer appear to work properly with respect to interfaces.

**Description**:
If I use the concrete type for a property in my Schema, I can use that property's generated Filter type as expected, but if I refer to the type by interface, the filter no longer works.

**Example**:

Given a Schema:
```
type Person implements SentientBeing {
  id: ID!
  email: String!
}

type Ship {
  id: ID!
  name: String!
  captain: SentientBeing! @relation(name: "PILOTS", direction: "IN")
}
```

The following query will not return any Ships:

```
query GetShipsByCaptainEmail (
  $email: String!
) {
  Ships(filter: { captain: { email: $email } }) {
    id
  }
}
```

However, if in the schema one changes the value of `Ship.captain` from `SentientBeing!` to `Person!`, the query will return the expected `Ships`.

**Comment by johnymontana** [comment]
This should now be fixed, please reopen if you're still seeing this problem.
