### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by bebbi** [neo4j-graphql/neo4j-graphql-js#41]
@johnymontana Would you accept a PR that adds automatic code formatting using [prettier](https://github.com/prettier/prettier) on commits?

**Comment by bebbi** [comment]
Yes, it's great!
OK I'll PR that - will just wait for @fwanicka  on #40 to avoid merge conflicts.
For other branches, I think running prettier first should normally make rebase work fine.

**Comment by frankwanicka** [comment]
Great idea. My pull request has been merged.
