### ISSUE TITLE
schemaDirectives

### ISSUE THREAD

**Issue by hyferg** [neo4j-graphql/neo4j-graphql-js#410]
Hello, I've followed this article to implement custom schema directives to no avail.
https://blog.grandstack.io/authorization-in-graphql-using-custom-schema-directives-eafa6f5b4658

I get a 
> Error: Unknown directive "isAuthenticated".
error.

Is this feature supported? The github repo tied to that article did not actually do what they said in the article.

**Comment by hyferg** [comment]
```
class isAuthenticatedDirective extends SchemaDirectiveVisitor {
    static getDirectiveDeclaration(directiveName, schema) {
        return new GraphQLDirective({
            name: "isAuthenticated",
            locations: [DirectiveLocation.FIELD_DEFINITION]
        });
    }
    visitFieldDefinition (field) {
        field.resolve = async () => {
            console.log('nothing');
            return "nothing";
        };
    }
}
```
and 
```
const schema = makeAugmentedSchema({
    typeDefs,
    schemaDirectives: {
        isAuthenticated: isAuthenticatedDirective
    }
});

```

**Comment by hyferg** [comment]
sorry I did not include the directive declaration inside of my typeDefs as 

```
const typeDefs = `

directive @isAuthenticated on FIELD_DEFINITION

...
```

serves me right for using this library before understanding the underlying tools. So many tools....

**Comment by benjamin-rood** [comment]
Hey buddy,

You don't need to implement this manually yourself :slightly_smiling_face:
https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization.html#enabling-auth-directives

```
import { makeAugmentedSchema } from "neo4j-graphql-js";

const schema = makeAugmentedSchema({
  tyepDefs,
  config: {
    auth: {
      isAuthenticated: true,
      hasRole: true
    }
  }
})
```

**Comment by hyferg** [comment]
My use case involves applying authentication and other directives to the mutations on a granular level. Additionally my authentication server returns roles like

```
permissions: [ query:all ]
```
rather than
```
role: [ query:all ]
```

**Comment by benjamin-rood** [comment]
No, you will need to define manual mutations, for sure.
