### ISSUE TITLE
Can't augment schema with filters for extended types.

### ISSUE THREAD

**Issue by leefreemanxyz** [neo4j-graphql/neo4j-graphql-js#413]
Hello, 

I think there are two parts to my issue here. I'm attempting to use inferSchema to generate my typeDefs, but I'm running into the issue that I have some multivalent relationships (a Document node is joined to Product, Item and ERPItems nodes using a :DOCUMENT_FOR relationship). This is not currently supported in the library.

As a result of this I am attempting to combine the generated types returned by inferSchema, with my own custom types, and passing the whole lot to makeAugmentedSchema. I pass it in like this:

```

const createCombinedSchema = (generatedTypeDefs) =>
  makeAugmentedSchema({
    typeDefs: `${generatedTypeDefs} ${customTypeDefs}`,
    resolvers: customResolvers,
    config: { mutation: false },
    allowUndefinedInResolve: true,
  });
```

Custom typeDefs would normally be required when we have written our own cypher directives, so I wouldn't be concerned about schema augmentation (as this library doesn't support filtering on @\cypher fields yet), but because of the aforementioned issue with multivalent relationships I want to add the @\relations to our custom typeDefs and use the schema augmentation in order to generate filters. 

With a big abbreviation of code, I'm looking to pass the following (and similar for other types) into makeAugmentedSchema:
 ```
// this will come from the generatedTypeDefs
type Item {
   _id: Long!
   longDescription: String
   manufacturerPartNumber: String
   partNumber: String!
   productFigureNumbers: String
   sequence: String
   shortDescription: String!
   tracepartsPartId: String
   has_feature: [Feature] @relation(name: "HAS_FEATURE", direction: "OUT")
   HAS_FEATURE_rel: [HAS_FEATURE]
   products: [Product] @relation(name: "HAS_ITEM", direction: "IN")
}
//this will be from the customTypeDefs
extend type Item{ 
    documents: [Document] @relation(name: "DOCUMENT_FOR", direction: "IN")
}
```

In this case, products will have the filter/first/offset arguments available, but documents will not. 

Is this possible to fix within the library (either by supporting multivalent types or ensuring that extended types get augmented too), or should I attempt to make changes to the relationships in the database instead (replace DOCUMENT_FOR with DOCUMENT_FOR_PRODUCT, DOCUMENT_FOR_ITEM etc.)? (Or I could manually edit the types generated by inferSchema, but that is quite obviously less appetising...)

**Comment by johnymontana** [comment]
Hey @leefreemanxyz - this should be fixed now. Could you give it a try with v2.13.0 and let us know if that works?

**Comment by leefreemanxyz** [comment]
Hey, I've just updated to 2.14.0 - it works (and there are some other really nice quality of life improvements - thank you!)
