### ISSUE TITLE
Nested filtering returns empty arrays

### ISSUE THREAD

**Issue by antikvarBE** [neo4j-graphql/neo4j-graphql-js#446]
Hello friends,

For some reason, I'm unable to use advanced nested filtering in my schema. What am I doing wrong?

Schema
```graphql
type User {
  managedPodcasts: [UserPodcastEditorOf]
  ...
}

type Podcast {
  editors: [UserPodcastEditorOf]
  ...
}

type UserPodcastEditorOf @relation(name: "EDITOR_OF") {
  from: User
  to: Podcast
  ...
}
```

Query
```graphql
Podcast(podcastId: $podcastId, first: 1) {
  editors(filter: { User: { uuid: $uuid } }) {
    User {
      uuid
    }
  }
}
```

Result
```json
"Podcast": [
  {
    "editors": [] <-- No luck!
  }
]
```

However, if I remove filters from editors, I get one result:

New query
```graphql
Podcast(podcastId: $podcastId, first: 1) {
  editors { # Notice the absence of filters
    User {
      uuid
    }
  }
}
```

Result
```json
"Podcast": [
  {
    "editors": [
      {
        "User": {
          "uuid": "some_uuid" <-- Luck
        }
      }
    ]
  }
]
```

Strangely enough, filtering from User through the relationship to Podcast ("managedPodcasts") with a similar filter works fine. So:

```graphql
User(uuid: $uuid, first: 1) {
    managedPodcasts(filter: { Podcast: { podcastId: $podcastId } }) {
      podcastId
    }
}
```
does yield results.

Any help is highly appreciated.

**Comment by NawarA** [comment]
I can confirm this bug exists. We're experiencing the same thing. Furthermore, sorting doesnt work on nested either

**Comment by antikvarBE** [comment]
@NawarA , ok it's comforting to know I'm not misinterpreting official documentation. Right now I'm simply returning everything and filter it all myself in JavaScript. Hacky but I'll survive. I guess you're doing the same thing.

**Comment by NawarA** [comment]
Yeah, but it sucks to not have the database be able to filter. This bug forces us to download too much data to the client, and do additional client-side work, because the database is unable to filter.

This needs to be patched right away, so we have normal GraphQL behavior.

**Comment by NawarA** [comment]
@johnymontana thank you!

**Comment by antikvarBE** [comment]
@johnymontana ,

I actually still experience this issue using "neo4j-graphql-js": "2.14.4" with Neo4j CE 4.1.1. What am I doing wrong? Do other people report this the same thing or am I the only one?
