### ISSUE TITLE
Blocker on authorization

### ISSUE THREAD

**Issue by bebbi** [neo4j-graphql/neo4j-graphql-js#46]
I'm hyped by this libs promise - one roundtrip per query :+1:

There's one thing that looks like a no-go for us though: it doesn't support authorization.

For example:

Given a model

    type Item {
      id
      content
      isPrivate
      ownerId
    }

one would need to be able to attach an authorizer to the resolver like so:

    isAuthorized(viewer, item) => !item.isPrivate || item.ownerId === viewer.userId

However, if the user queries

    {
      getItem(id: 10) {
        content
      }
    }

that skips the necessary attribute `isPrivate` for authorization, in the example leading to an unauthorized pass.

Solution: After some thinking about available solutions, how about a custom `@fetch` directive to always add annotated fields to a query of the parent? Then let graphql filter it out for the client.
@johnymontana I would love to hear your thoughts on this.

**Comment by johnymontana** [comment]
We've implemented a few different options for authorization described [here](https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization.html) including:

* GraphQL authorization schema directives
* Injecting Cypher parameters from context object, and
* Middleware support

Please re-open this issue (or create a new one) if these authorization options don't address your use case.
