### ISSUE TITLE
Query using interface, without inline fragments, doesn't work

### ISSUE THREAD

**Issue by MImranAsghar** [neo4j-graphql/neo4j-graphql-js#471]
Hi, I am using neo4j-graphql-js version 2.14.3, I am trying to implement interface. After adding interface, I am able to create interface types, and query interface with the __typename like so query{ interface{ __typename ... on Image { id } } }....and this works. But when i try this without __typename ... on Image {id }, I expect the query to return all the types that implement interface. So I am talking about a query like query{ interface{  id } } However, this won't work. Can anyone see why? I get this error Abstract type Content must resolve to an Object type at runtime for field Query.Content with value { FRAGMENT_TYPE: null }, received \"null\".
Specifically this won't work https://grandstack.io/docs/graphql-interface-union-types/#query-field

**Comment by johnymontana** [comment]
Hi @MImranAsghar - could you please include a minimal example of the type definitions you are using so we can reproduce this?

**Comment by MImranAsghar** [comment]
Hi, I am using defining these as follows in the schema

`
interface Content {
  id: ID!
  label: String!
  height: Int!
  width: Int!
  dateCreated:Float
  storageUrl: String!
  originalFileUrl:String
  type: String
  format: String 
  description: String
}

type Image implements Content{
  id: ID!
  label: String!
  height: Int!
  width: Int!
  dateCreated:Float
  storageUrl: String!
  originalFileUrl:String
  type: String
  format: String 
  description: String
  parentAnnotation: Annotation
    @cypher(
      statement: "MATCH (a:Annotation)-[:hasResource]->(this) RETURN a"
    )
  parentCanvas: Canvas
    @cypher(
      statement: "MATCH (c:Canvas)-[:hasThumbnail]->(this) RETURN c"
    )
}

type Video implements Content{
  id: ID!
  label: String!
  height: Int!
  width: Int!
  duration: Int
  dateCreated:Float
  storageUrl: String!
  originalFileUrl:String
  thumbnailUrl: String
  type: String
  format: String 
  description: String
  parentAnnotation: Annotation
    @cypher(
      statement: "MATCH (a:Annotation)-[:hasResource]->(this) RETURN a"
    )
}
`

**Comment by MImranAsghar** [comment]
Hi, I was wondering whether you were able to reproduce the above error?

**Comment by MImranAsghar** [comment]
Reason i am wondering is b/c i need to use this feature in a project w a deadline...wondering if this could be fixed soon.

**Comment by michaeldgraham** [comment]
Hey @MImranAsghar, I'm wondering if there exist some nodes in your database that have a `Content` label but neither an `Image` nor a `Video` label. Due to the way fragmented queries on interface types are translated, this situation would result in the error you're seeing because when querying all `Content` labeled nodes, some nodes would not be identified as either an `Image` or a `Video`, leaving the dynamically set `FRAGMENT_TYPE` property to be `null`.

**Comment by rbennell** [comment]
@MImranAsghar seems to be buggy for us too. maybe a bit late for you, but for anyone else in the contents field you could always write `@cypher(statement: MATCH (this)-[:hasResource]->(c) WHERE (c:Video) OR (c:Image) RETURN (c))`. Bit of a hack, but probably good enough if you're not using the interface too widely.

**Comment by loicmarie** [comment]
I was facing this issue, but thanks to @michaeldgraham I have found out some missing labels in my graph.
After fixing it, it works fine now
