### ISSUE TITLE
Error: Command failed with ENOENT: yarn install

### ISSUE THREAD

**Issue by harshil4076** [neo4j-graphql/neo4j-graphql-js#472]
Throws this error when the GRAND stack starter is run. It installs everything but when it comes to web-react , throws the above error

**Comment by johnymontana** [comment]
Closing this issue as this sounds like a problem the the GRANDstack starter project.

@harshil4076 - could you please open an issue here to track: https://github.com/grand-stack/grand-stack-starter/issues
