### ISSUE TITLE
[Regression] 2.14.4 Breaks Nested Filters Previously Working in 2.14.0

### ISSUE THREAD

**Issue by Phylodome** [neo4j-graphql/neo4j-graphql-js#477]
The following query, working fine in `2.14.0`, no longer returns any results in `2.14.4`.

```
query getLandscape($email:String){
  Landscape (filter:{agent:{Person: {email:$email}}}){
    id
    agent {
      status
      Person{
        email
      }
    }
  }
}
```

As this was a patch update, I doubt there was any intentional changes to the interface, so I'm assuming this is a regression that wasn't caught in testing / code review.

Here's the generated Neo4j query:
```
MATCH (`landscape`:`Landscape`) WHERE (EXISTS((`landscape`)-[:HAS_LANDSCAPE]->(:Landscape)) AND ALL(`person_filter_landscape` IN [(`landscape`)-[`_person_filter_landscape`:HAS_LANDSCAPE]->(:Landscape) | `_person_filter_landscape`] WHERE (ALL(`person` IN [(`landscape`)<-[`landscape_filter_person`]-(`_person`:Person) | `_person`] WHERE (`person`.email = $filter.agent.Person.email))))) RETURN `landscape` { .id ,agent: head([(`landscape`)<-[`landscape_agent_relation`:`HAS_LANDSCAPE`]-(:`Person`) | landscape_agent_relation { .status ,Person: head([(:`Landscape`)<-[`landscape_agent_relation`]-(`landscape_agent_Person`:`Person`) | landscape_agent_Person { .email }]) }]) } AS `landscape`
```

and the associated context:

```
{
   "offset": 0,
   "first": -1,
   "filter": {
     "agent": {
       "Person": {
         "email": "[name-redacted]@[domain-redacted].com"
       }
     }
   }
 }
```

**Comment by Phylodome** [comment]
Looking at the diff b/w the generated code, it appears that 2.14.0 flips the relevant relationship directions:
![Screen Shot 2020-07-16 at 4 57 04 PM](https://user-images.githubusercontent.com/241837/87733705-63f80d80-c785-11ea-9421-72ac131bf939.png)

**Comment by michaeldgraham** [comment]
Hey there! I just finished a fix for what went wrong, it should be submitted once I put together some new tests. Thanks for sharing this, I had accidentally broken this behavior as it didn't have tests yet :)
