### ISSUE TITLE
Add support for node 12 and 14 to testing platform

### ISSUE THREAD

**Issue by gwvandesteeg** [neo4j-graphql/neo4j-graphql-js#479]
Currently the testing system only tests on node 8 and 10
* v8 is EOL (it can be deprecated out of testing to reduce compute resources if desired)
* v10 has an EOL of 2021-04-30
* v12 has an EOL of 2022-04-30 (current LTS)
* v14 has an EOL of 2023-04-30

As per: https://nodejs.org/en/about/releases/

This ensures that the platform continues to function using the more recent releases of node and any breaking changes can be quickly identified.

**Comment by johnymontana** [comment]
Fixed in 5abfe4369aebda9077e8a261d4c3699c474691e3 and 32101dac00f83555408894dab30376564883b1fd
