### ISSUE TITLE
query fragments not working

### ISSUE THREAD

**Issue by bebbi** [neo4j-graphql/neo4j-graphql-js#48]
fragment myTitle on Movie {
      title
    }

    query getMovie {
      Movie(title: "River Runs Through It, A") {
        ...myTitle
      }
    }

returns null, while replacing ...myTitle with title returns the movie title.

**Comment by johnymontana** [comment]
This should be fixed in https://github.com/neo4j-graphql/neo4j-graphql-js/commit/dc0398e69ee99d450902a872ac4c28413c01d239 and is included in v0.1.14 on NPM.

Please let us know if this fix works for you. Thanks!

**Comment by bebbi** [comment]
This works now!
