### ISSUE TITLE
subquery variable defaults are ignored

### ISSUE THREAD

**Issue by bebbi** [neo4j-graphql/neo4j-graphql-js#49]
I've experienced that pagination variable defaults have no effect on the query (e.g. offset/first).

As an example, the project's test schema has a field `similarity` on type `Movie`

```
similar(first: Int = 3, offset: Int = 0): [Movie]
```

It looks like the defaults for those variables are not correctly considered in the query.
When playing, I've found that generally some variables may be in the wrong place.

Here is a commit 

I've added a commit [here](https://github.com/bebbi/neo4j-graphql-js/tree/issuepagination) with one test added (default vars) and one changed (vars in different places than expected) to show what I mean. The changed queries, rather than the originals, seem to work for me as expected on the movie dataset.

**Comment by johnymontana** [comment]
This has been fixed in 56d04c7f7cc8814f9599c765a3d40a86a787eba2 - previously `first`, `offset`, and `orderBy` were explicitly excluded from the parameters passed to the subqueries used in Cypher directives.
