### ISSUE TITLE
How to retrieve request headers from context

### ISSUE THREAD

**Issue by rohanray** [neo4j-graphql/neo4j-graphql-js#5]
I'm currently working on an ecommerce project where in we currently have MongoDB as the persistence store behind graphql. I'm trying to see the feasibility of neo4j to persist a few of our models(collections) since they have a specific hierarchy which favours neo4j compared to mongo. Hence, I'm glad to have stumbled upon this project.

Also, we use JWT for authenticated requests which are sent in request headers. However, as per the guide the current context function which returns the neo4j driver doesn't suit this scenario since I don't have access to my request headers anymore.

Is there any way I can pass on my request headers to my resolvers? I'm sure this would be a very common scenario.

**Comment by cricrio** [comment]
I think you can put the request headers in your context like this : 
```
function context(headers, secrets) {

  if (!driver) {
    driver = neo4j.driver(secrets.NEO4J_URI || "bolt://localhost:7687", neo4j.auth.basic(secrets.NEO4J_USER || "neo4j", secrets.NEO4J_PASSWORD || "letmein"))
  }
  return {
   driver,
   headers
};
}

**Comment by johnymontana** [comment]
Yes - exactly. I updated [the example](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/example/graphql-tools/movies.js) to include that here: 52c4497190cd56fd4715f17f5fb74c1cc1d5a6e3 . Thanks @cricrio 

In the movies example the request headers are passed through `graphqlExpress`:

~~~
server.use('/graphql', bodyParser.json(), graphqlExpress(request => ({
  schema,
  rootValue,
  context: context(request.headers, process.env),
})));
~~~

Inside the resolver you can then access the headers:

~~~
Movie(object, params, context, resolveInfo) {

      const headers = context.headers;
      // do something with request headers
      // ...
      return neo4jgraphql(object, params, context, resolveInfo);
    }
~~~

Currently, we don't include any auth logic in `neo4jgraphql` - we're still looking at what makes sense there. If you have any requests/suggestions would love to hear them.

**Comment by rohanray** [comment]
Thanks @cricrio ! Works like a charm!

**Comment by rohanray** [comment]
@johnymontana I think the formal Graphql specs has always suggested **not** to include Authentication within graphql itself. However, I guess if we have access to the original request including headers; authentication and/or authorization can always be performed within resolvers; using an express middleware.

IMO, we should not include any authentication/authorization API in neo4jgraphql - just my 2 cents.

**Comment by jexp** [comment]
If you look at what graphcool does and also fb that resolves authorisation in the data backend then the state is much more varied

I think we should at least have it as an option
