### ISSUE TITLE
How can I add custom JS logic for a field annotated with @cypher?

### ISSUE THREAD

**Issue by amoe** [neo4j-graphql/neo4j-graphql-js#509]
Hi, imagine I have some schema like this (fictional):

```
type Business {
     waitTime: Int @cypher(statement: "MATCH (this)-[:HAS_DELAY]->(d:Department) RETURN d.delay")
}
```

I want to use some custom logic in JS similar to the example in the [documentation](https://grandstack.io/docs/graphql-custom-logic/#implementing-custom-resolvers).  I specifically can't do this logic in Cypher, it has to be done within the JS environment.

```
const resolvers = {
  Business: {
    waitTime: (obj, args, context, info) => {
      // XXX: somehow get delay from running Cypher
      return delay * 0.8;
    }
  }
};
```

That is, I need to combine both things: I need to both execute the Cypher and also postprocess the result with a JS function.  Is this possible at present?  I tried combining them using `neo4jgraphql` but I received strange errors about `astNode`.  I understand it may not be possible due to neo4j-graphql-js's bundling of Cypher queries.  Is there any workaround for those of us who may be willing to sacrifice speed for correctness?  I'm also willing to do the query imperatively within the resolver if necessary, rather than using `@cypher`.

**Comment by michaeldgraham** [comment]
Hey @amoe, would you try this example?

With the following data,

```graphql
CREATE (b:Business)-[:HAS_DELAY]->(d:Department { delay: 2}) RETURN *
```

And these typedefs and resolvers,

```js
const typeDefs = gql`
  type Business {
    waitTime: Float @cypher(statement: "MATCH (this)-[:HAS_DELAY]->(d:Department) RETURN d.delay")
  }
`;

const resolvers = {
  Business: {
    waitTime: (businessData, args, context, info) => {

      // The first argument for a field resolver provides the resolved data for the parent type. So, 
      // post-processing data resolved by using neo4jgraphql with generated resolvers, can be done in this way:

      const waitTime = Number.isInteger(businessData.waitTime) ? businessData.waitTime : 1;

      return waitTime * 0.8;
    }
  }
};
```

This query, 
```graphql
query {
  Business {
    waitTime
  }
}
```

Should result in this data:
```js
{
  "data": {
    "Business": [
      {
        "waitTime": 1.6
      }
    ]
  }
}
```

**Comment by amoe** [comment]
@michaeldgraham That works perfectly -- thanks so much for the help.  :)
