### ISSUE TITLE
Verbose, unstoppable logging as of v0.1.18

### ISSUE THREAD

**Issue by cooperka** [neo4j-graphql/neo4j-graphql-js#52]
It looks like several leftover debugging statements got merged to master in https://github.com/neo4j-graphql/neo4j-graphql-js/commit/af233b9484c95afd5c29e07615b3691b974c0ee3. All queries are now logged to console, and they are double-logged if `debug` is `true` (which is now the default).

I'm not sure which of those changes are wanted vs. unwanted; @johnymontana do you mind taking a look? Cheers.

**Comment by johnymontana** [comment]
Thanks for catching - looks like I missed moving those console.log statements into the `if (debug)` block. Should be fixed now.

**Comment by cooperka** [comment]
Thanks @johnymontana -- debug mode now also defaults to `true`, is that intentional? (https://github.com/neo4j-graphql/neo4j-graphql-js/commit/af233b9484c95afd5c29e07615b3691b974c0ee3#diff-1fdf421c05c1140f6d71444ea2b27638L17)

**Comment by johnymontana** [comment]
Yes, given the development focused nature of the library we've chosen to keep debug mode on by default.
