### ISSUE TITLE
Order By with _Neo4jDateTime { formatted } causes error. Resolve function for \"_Neo4jDateTime.formatted\" returned undefined

### ISSUE THREAD

**Issue by CraigDeverall** [neo4j-graphql/neo4j-graphql-js#524]
Version: neo4j-graphql-js-2.15.0

This query returns with an error:

`query latestProjectionsForDepartment($departmentIds: [ID!]) {
    Department (filter: {id_in: $departmentIds}) {
        name
        projectionsSyncEvents(first: 1 orderBy: lastUpdatedDate_desc) {
            projections(orderBy: startDate_desc) {
              crewWeeks
              startDate {
                formatted
              }
              endDate {
                formatted
              }
            }
        }
    }
}`

![image](https://user-images.githubusercontent.com/3393968/96504009-9ba8b100-12b0-11eb-839e-73593d0aaa9e.png)

The Error: 
![image](https://user-images.githubusercontent.com/3393968/96504162-d27ec700-12b0-11eb-8926-64234e163188.png)
`"errors": [
    {
      "message": "Resolve function for \"_Neo4jDateTime.formatted\" returned undefined",
      "locations": [
        {
          "line": 8,
          "column": 11
        }
      ],
      "path": [
        "Department",
        0,
        "projectionsSyncEvents",
        0,
        "projections",
        0,
        "startDate",
        "formatted"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Resolve function for \"_Neo4jDateTime.formatted\" returned undefined",
            "    at /digi/app/projector_backend_grand/sprint13v3/node_modules/graphql-tools/src/makeExecutableSchema.ts:104:13",
            "    at field.resolve (/digi/app/projector_backend_grand/sprint13v3/node_modules/graphql-extensions/src/index.ts:274:18)",
            "    at field.resolve (/digi/app/projector_backend_grand/sprint13v3/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)",
            "    at resolveFieldValueOrError (/digi/app/projector_backend_grand/sprint13v3/node_modules/graphql/execution/execute.js:467:18)",
            "    at resolveField (/digi/app/projector_backend_grand/sprint13v3/node_modules/graphql/execution/execute.js:434:16)",
            "    at executeFields (/digi/app/projector_backend_grand/sprint13v3/node_modules/graphql/execution/execute.js:275:18)",
            "    at collectAndExecuteSubfields (/digi/app/projector_backend_grand/sprint13v3/node_modules/graphql/execution/execute.js:713:10)",
            "    at completeObjectValue (/digi/app/projector_backend_grand/sprint13v3/node_modules/graphql/execution/execute.js:703:10)",
            "    at completeValue (/digi/app/projector_backend_grand/sprint13v3/node_modules/graphql/execution/execute.js:591:12)",
            "    at completeValueCatchingError (/digi/app/projector_backend_grand/sprint13v3/node_modules/graphql/execution/execute.js:495:19)"`

But if I don't use the "formatted" date from _Neo4jDateTime it works fine:

It also works fine if I leave the { formatted } but remove the orderBy

**Comment by CraigDeverall** [comment]
I ran into this same problem again the next day

![image](https://user-images.githubusercontent.com/3393968/96657666-4a2b1f80-139f-11eb-99a9-a304f1e1f2ad.png)

Uncommenting the commented code cause the same issue.

In summary this actually seems to mean I cant use the formatted date key if I am ordering by a date.

**Comment by revozhang** [comment]
I am having the same issue too. When a datetime has orderBy, formatted and timezone return null.

**Comment by CraigDeverall** [comment]
This also seems to be an issue with the 'timezone' key
