### ISSUE TITLE
Why does this project use the #npm branch of graphql-js?

### ISSUE THREAD

**Issue by wheresrhys** [neo4j-graphql/neo4j-graphql-js#54]
It feels very risky to use this in anything other than prereleases of this library. If you were to switch to the main npm releases it would give me and my team a lot more confidence in using it - we are hoping to make graphql the main read interface for one of our projects

**Comment by johnymontana** [comment]
Good point - that was being used to develop some experimental ways of handling mutations (with schema extensions which are available in the master branch of graphql-js, but not the latest release).

We don't actually need this feature so I've switched back to using the latest graphql-js release. Thanks for pointing this out!
