### ISSUE TITLE
Error when mapping enum to internal values in resolver

### ISSUE THREAD

**Issue by CostaFernando** [neo4j-graphql/neo4j-graphql-js#559]
Hi guys,

I have an enum in my schema that I need to map with internal values. I followed the Apollo Server documentation to do this: https://www.apollographql.com/docs/apollo-server/schema/scalars-enums/#internal-values. But I'm getting the error `Cannot read property 'name' of undefined` when I try to get any relationship in any type, even if it is not related at all with the problematic enum.
This is the enum:
```
//schema.graphql
enum MIMEType {
	IMAGE_PNG
	IMAGE_GIF
	IMAGE_JPEG
	AUDIO_MPEG
	AUDIO_WEBM
	AUDIO_OGG
	AUDIO_WAV
	TEXT_PLAIN
	TEXT_CSV
}
//used in this query
type Query {
	awsS3PreSignedUploadUrl(
		fileName: String!
		contentType: MIMEType!
	): PreSignedUploadUrl!
}
```

This is the internal value mapping in resolvers.js:
```
//resolvers.js
export const resolvers = {
    MIMEType: {	
		IMAGE_PNG: "image/png",	
		IMAGE_GIF: "image/gif",	
		IMAGE_JPEG: "image/jpeg",	
		AUDIO_MPEG: "audio/mpeg",	
		AUDIO_WEBM: "audio/webm",	
		AUDIO_OGG: "audio/ogg",	
		AUDIO_WAV: "audio/wav",	
		TEXT_PLAIN: "text/plain",	
		TEXT_CSV: "text/csv",	
	},
}
```

This seems to make sense, given the Apollo Server documentation. But when I try to access a relationship in any type (not related at all with the enum), I get the following error.

![image](https://user-images.githubusercontent.com/17749414/102162577-2993b900-3e68-11eb-9998-893a2f221f25.png)

This is breaking my entire app. Am I doing something wrong?

**Comment by lfritsche** [comment]
I'm facing the same issue when providing mapping values. Removing the enum field within resolvers allows the query to be processed.
```js
"TypeError: Cannot read property 'name' of undefined",
            "    at .../api/node_modules/neo4j-graphql-js/dist/translate.js:2361:14",
            "    at Array.find (<anonymous>)",
            "    at processFilterArgument (.../api/node_modules/neo4j-graphql-js/dist/translate.js:2360:29)",
            "    at relationTypeFieldOnNodeType (.../api/node_modules/neo4j-graphql-js/dist/translate.js:298:34)",
            "    at buildCypherSelection (.../api/node_modules/neo4j-graphql-js/dist/selections.js:511:80)",
            "    at recurse (.../api/node_modules/neo4j-graphql-js/dist/selections.js:97:33)",
            "    at buildCypherSelection (.../api/node_modules/neo4j-graphql-js/dist/selections.js:544:17)",
            "    at recurse (.../api/node_modules/neo4j-graphql-js/dist/selections.js:97:33)",
            "    at buildCypherSelection (.../api/node_modules/neo4j-graphql-js/dist/selections.js:544:17)",
            "    at nodeQuery (.../api/node_modules/neo4j-graphql-js/dist/translate.js:1071:69)"
```
            
It seems like Apollo's internal values beeing resolved that way is not compatible right now.

**Comment by CostaFernando** [comment]
@michaeldgraham , @johnymontana , Apollo's internal values mapping is not supported by neo4j-graphql.js?

**Comment by CostaFernando** [comment]
With neo4j-graphql.js 2.19.1, it worked as expected! @lfritsche , I suggest that you upgrade the neo4j-graphql.js version and see if it works.
