### ISSUE TITLE
Custom mutation resolvers

### ISSUE THREAD

**Issue by johnstonmatt** [neo4j-graphql/neo4j-graphql-js#566]
Hey all, Thanks for your work on this!

I'm hoping to add a resolver to a node mutation such that I can intercept the a Node that is about to be persisted to neo4j, and execute arbitrary code, because this node depends on some data from a 3rd party API for some of it's properties, and that API also triggers behavior in it's own right.

It seems like resolvers in neo4j-graphql-js are just for Queries, and are limited to fields.

Do you have any recommendations for adding functionality that is triggered at the time of node creation, that can contribute to the fields of the new node?

Could I help with adding support for mutation resolvers?

**Comment by johnstonmatt** [comment]
Personally I would like the resolver function signature to match in `neo4j-graphql-js` and normal graphql

**Comment by michaeldgraham** [comment]
Hey there - we have support for this so I'm not sure what might be happening here, could you share your schema so I can try to reproduce the issue you're experiencing?

**Comment by johnstonmatt** [comment]
Hey Michael, you're right, there is no issue here. 

I was just causing problems by passing my root Mutation resolvers directly to Apollo-Server instead of to the `neo4j-graphql-js` resolver object, which caused issues. 

After I used the mutation name that `neo4j-graphql-js` generated for me and passed it to the library instead everything worked, I must have just been too tired last night lol

Thanks for your help!

**Comment by michaeldgraham** [comment]
Oh that's wonderful news! I'll be around if you run into anything else ☺️

**Comment by dmoree** [comment]
@johnstonmatt @michaeldgraham 
Is there an example that can be pointed to of this functionality? The section [Implementing Custom Resolvers](https://grandstack.io/docs/graphql-custom-logic#implementing-custom-resolvers) of the documentation seems to address only a simple use case.
