### ISSUE TITLE
pass parameters to @cypher directives

### ISSUE THREAD

**Issue by jexp** [neo4j-graphql/neo4j-graphql-js#58]
e.g.

` users(id: ID, name: String, first: Int = 10, offset: Int = 0): [User] @cypher(statement:"MATCH (u:User:StackOverflow) RETURN u LIMIT $first+$offset SKIP $offset")`

results in

```
WITH apoc.cypher.runFirstColumn("MATCH (u:User:StackOverflow) RETURN u LIMIT $first+$offset SKIP $offset", {}, True) AS x UNWIND x AS user
    RETURN user { .name ,questions: [(user)-[:POSTED]->(user_questions:Question{}) | user_questions { .title }][..3] } AS user SKIP 0 LIMIT 10
{ first: 10, offset: 0 }
```

**Comment by wheresrhys** [comment]
As an additioanl requirement, it would be powerful to be able to use these parameters to modify the underlying cypher, not just as parameters passed to the cypher e.g. to modify the depth of recursion allowed when traversing relationships

**Comment by JobinMathewP** [comment]
Is there any solution or hack for this?

**Comment by johnymontana** [comment]
We were explicitly excluding `first`, `offset`, and `orderBy` parameters from being passed to the Cypher query as these were handled elsewhere, but I can see the value in having these available in the Cypher statement used in the directive.
