### ISSUE TITLE
Convert result of query into boolean property

### ISSUE THREAD

**Issue by wheresrhys** [neo4j-graphql/neo4j-graphql-js#60]
So for example, if I a particular node has no related nodes matching a given relationship & type, then the property's value will be `false`, otherwise `true`

Essentially converting the result of a `@relation` directive to boolean based on the length of the result

**Comment by johnymontana** [comment]
Hey @wheresrhys - 

I think you could accomplish this with the use of `@cypher` directive. Would something like this work for your use case?

```
type Person {
  name: String
  hasFriend: Boolean @cypher(statement: "RETURN EXISTS((this)<-[:FRIEND]-(:User))")
}
````

**Comment by johnymontana** [comment]
In addition to the `@cypher` directive option described above you could also accomplish this using the `filter` functionality:

given

```
type Person {
  name: String
  friends: [Person] @relation(name: "FRIENDS", direction: "OUT")
}
```

this query will filter for only `Person` nodes that have at least one `FRIENDS` relationship

```
Person(filter: {friends_not: null}) {
  name
}
```

Closing the issue, but please reopen if either of these approaches don't address your use case.
