### ISSUE TITLE
Hook for manual Resolvers into neo4j-graphql-js

### ISSUE THREAD

**Issue by NachtmahrEDM** [neo4j-graphql/neo4j-graphql-js#64]
Sometimes, there may be the need to write manual resolver-code as given in my example, may it the use of variables or that a query requires more complex methods or the inout from another database. 

https://pastebin.com/y9Q63KjY

Problem is that now, with my manual resolver-code given, the context is gone missing and I can't treverse any further with neo4jgraphql-objects. I wish that there would be

1. The possibility of passing variables to graphql-js so that I can use the @cypher-directive instead or that
2. I can resolve my data with matching context to hook it back into neo4j-graphql-js.

**Comment by johnymontana** [comment]
Hey @NachtmahrEDM - it looks like the pastebin linked has been removed. Could you please add your example code to this issue again? I'm not quite sure how to interpret without seeing your example. Thanks!

**Comment by johnymontana** [comment]
Closing as I can't access your example, but please reopen if your issue hasn't been resolved.
