### ISSUE TITLE
Documenting How to Replace Generated Reducers and Mutations

### ISSUE THREAD

**Issue by YizYah** [neo4j-graphql/neo4j-graphql-js#66]
Could he have some examples (maybe even just in the documentation) that show how to replace generated reducers with versions that use authentication?  And also for reducers for generated mutations?  i.e. 

1.  here's a sample generated reducer;
2. here's an example of using auth embedded within it;
3. here's what you can do with middleware.  

Also,
1.  here's a generated mutation and it's reducer; 
2. as above
3. as above...

**Comment by johnymontana** [comment]
We've added some authorization features as described [here in the docs](https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization.html) along with some examples for using with the generated mutations. Also, see the [authorization example app here](https://github.com/johnymontana/grand-stack-starter-auth0-demo) that includes both front-end and back-end examples.

Please reopen if this doesn't address your issue.
