### ISSUE TITLE
Check context.error in resolver

### ISSUE THREAD

**Issue by johnymontana** [neo4j-graphql/neo4j-graphql-js#71]
Would it be possible to insert something like this into generated resolvers:

           
```
if (ctx.error) {
               throw new Error(ctx.error);
            }
```

The problem is, we can add auth using middleware, but I don't know how to use it with the generated resolvers.  Currently, the only thing I can do is create a resolver like this that checks for an error before calling `neo4jgraphql`:

```
(object, params, ctx, resolveInfo) => {
            if (ctx.error) {
              throw new Error(ctx.error);
            }
            return neo4jgraphql(object, params, ctx, resolveInfo);
        }
```

If I have to do that for every resolver, aside from being a big pain, I won't be able to use the augmented functions.  You just need to give us one example in the documentation.

**Comment by YizYah** [comment]
[api.zip](https://github.com/neo4j-graphql/neo4j-graphql-js/files/2205988/api.zip)
Here's a zip of an api--exactly as developed with the last version of the GRANDstack starter and the changes that I suggest to the user in an article.  In the auth.js file I defined some middleware auth function templates that would update req.auth.error, but I assume that the same approach could be used with req.error, which I think would make more sense.

**Comment by johnymontana** [comment]
@YizYah I've added this in 1f71f721ca4baf37ddd15720d58ce5ad4d5309c6 and is now available on npm from 0.1.25. Please try it out and let me know if it works for you.

Initially I just check for `context.req.error` or `context.error` and throw an error if either is defined. So we'll need to inject the request object into the context, something like:


```
const server = new ApolloServer({
  schema: augmentedSchema,
  // inject the request object into the context to support middleware
  // inject the Neo4j driver instance to handle database call
  context: ({ req }) => {
    return {
      driver,
      req
    };
  }
});
```

There's a full example [here](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/example/apollo-server/movies-middleware.js) and a new test [here](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/test/test-middleware.js).

While all we're checking now is just for an error, this could be the basis for more integrated auth checking.

**Comment by YizYah** [comment]
@johnymontana works great!!  Now we're getting somewhere--I'm assuming that you've updated the GRANDstack starter to use 0.1.25.  

I think that you're completely correct--you're "just" checking for an error, but it opens the door for authentication, authorization, checking whether a user's payments are up-to-date, and essentially any middleware.  Practically speaking, there cannot be middleware without the ability to throw errors.  So I think that the package is much more useful now!

**Comment by johnymontana** [comment]
OK great. I'm closing this issue and we'll move on to adding more advanced auth checking features.
