### ISSUE TITLE
`onTypeConflict` is deprecated. Use schema transforms to customize merging logic.

### ISSUE THREAD

**Issue by joeflack4** [neo4j-graphql/neo4j-graphql-js#77]
## Description
When running `apollo-server`, I'm getting the following warning. I believe this is the result of using `onTypeConflict` in `mergeSchemas()` from `graphql-tools` [here in this file](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/f9ffbbc0e66deec75c705da69860b5632461dba2/src/augmentSchema.js#L73).

Not really sure how to specifically resolve this using Schema transforms, but there is [an open issue](https://github.com/apollographql/graphql-tools/issues/863) in `graphql-tools` asking for further elaboration.

**Comment by johnymontana** [comment]
This should have been resolved by #84. We're no longer using the `mergeSchemas` approach for augmenting the schema as that was problematic. Closing now, but please reopen if you see this issue again.

**Comment by joeflack4** [comment]
Thank you~
