### ISSUE TITLE
Use MERGE instead of CREATE in mutations

### ISSUE THREAD

**Issue by Duske** [neo4j-graphql/neo4j-graphql-js#83]
It would be cool if one could choose to use `MERGE` over `CREATE` in create-mutations. This way, one could avoid having too much duplicate nodes/relationships in the database since `UNIQUE` is deprecated.
Afaik, this is not possible yet with this library, isn't it?

**Comment by johnsonjo4531** [comment]
Maybe the driver could allow special directives on properties of schema objects named something like `@mergeOn`, so only those properties would be merged on.

**Comment by johnymontana** [comment]
I propose that we add a new category of generated mutation that uses `MERGE`. 

We currently have a convention for choosing the "primary key" a type (looking for non-null ID type, then fall back to nullable ID, etc) so we could use this approach for defining the property on which to `MERGE`. So for a given type `Person` we would generate the following mutations:

```
CreatePerson
MergePerson
UpdatePerson
DeletePerson
```

This should also be supported for relationships.

**Comment by appinteractive** [comment]
@johnymontana would that not be too much responsibility / implementation details on the client? Sounds to me like an antipattern. 

How about an directive on the Schema type? `@merge` or similar? Would be a more clean approach to me.

**Comment by johnymontana** [comment]
@appinteractive the only additional responsibility for the client would be choosing to use the create mutation or the merge mutation. Probably 9 times out of 10 merge is actually the appropriate semantic to avoid creating duplicate data.

Could you give an example of how a `@merge` directive would be used?

**Comment by appinteractive** [comment]
I think that the update mutation with a modifier would be the way to go. 

When the `type User @merge {` is present, the updateUser mutation would use MERGE instead of SET. I would prefer to keep the api clean where possible.

**Comment by appinteractive** [comment]
Maybe the `@merge` directive could also be used on a field to decide which field should be used for the merge? 

```type User {
   id: ID!
   username: String @merge
}```

**Comment by johnsonjo4531** [comment]
Sorry I'm kind of new to both graphql and cypher, so I may have not made complete sense in my last post. I just found out it's pretty simple to do the above with a `@cypher` directive on a mutation. So, maybe the library doesn't need to cover that case, but it could be nice to have.

```
input ArticleInput {
  id: ID
  headline: String
  webpage: WebPageInput!
}

input WebPageInput {
  url: String!
}

type Mutation {
  mergeInArticle(article: ArticleInput!): Article
    @cypher(
      statement: """
      MERGE (W:WebPage {url: $article.webpage.url})
      MERGE (A:Article) -[:HAS_WEBPAGE]-> (W)
        ON CREATE SET A.id = apoc.create.uuid(), A = apoc.map.removeKeys($article, ['webpage'])
      RETURN A
      """
    )
}
```

**Comment by johnymontana** [comment]
See https://github.com/neo4j-graphql/neo4j-graphql/pull/154 for inspiration / consistency

**Comment by maieulChevalier** [comment]
It seems to me that having a pattern like @appinteractive proposed : `type User @merge { ` would be optimal as I haven't yet encountered the case where I would need to both being able to create and merge on the same type. But there might be some cases where you'd need to.

But having this :
```
CreatePerson
MergePerson
UpdatePerson
DeletePerson
```
would be fine as well @johnymontana if it's more consistent with [neo4j-graphql/neo4j-graphql#154 ](https://github.com/neo4j-graphql/neo4j-graphql/pull/154)

Either way, having auto-generated MERGE would be amazing.

Any idea of when it would be implemented in neo4j-graphql-js?

**Comment by AshkanHovold** [comment]
We would also like this feature in our project. We have a situation where we need to check alot of ids an update if they exist otherwise create them.

**Comment by johnymontana** [comment]
Merge mutations have been added as an additional generated mutation operation. See the docs here: https://grandstack.io/docs/graphql-schema-generation-augmentation.html#merge-relationship
