### ISSUE TITLE
Wrap a $params object into neo4jgraphql resolvers

### ISSUE THREAD

**Issue by YizYah** [neo4j-graphql/neo4j-graphql-js#85]
Thread on Slack...

**Yisroel** [18 hours ago]
@lyonwj one little thing: it wold be nice if we could use `$params` in a cypher directive of a mutation declaration, the same way that you generate in `augmentSchema`.  Because:

-  the easiest way to overwrite a mutation is to call the generated one first and copy the query that gets sent to the console.  But it contains `$params`, which neo4jgraphql doesn't like when I use it...  
-  if I go through and add every property in the parameter list, then they all become mandatory unless I modify the parameter list to include default values.  E.g.

>         CreatePlatform(id: ID!, name: String="", paidThrough: String="", paymentID: String=""): Platform @cypher(statement: "CREATE (platform:Platform) SET platform += { id: $id , name: $name, paidThrough: $paidThrough , paymentID: $paymentID } RETURN platform")

I'm wondering if you could modify neo4jgraphql to group together all of the parameters of a declaration into `$params` automatically? (edited)

**lyonwj** [15 hours ago]
@Yisroel yea we could probably do that. Although I would if it would be less obvious for more simple cases. You're right that the reason I do it for the create mutations is so I can simply do `SET movie += $params`.

I see what you mean about that making the params required so I suppose wrapping in a `params` object is a good fix for that. Could you open an issue on Github? (Could just copy paste this thread in there)

**Comment by johnymontana** [comment]
Hey @YizYah - you should be able to achieve this by using an [Input type](https://graphql.github.io/learn/schema/#input-types). 

For example:

```
input PlatformInput {
  id: ID!
  name: String
  paidThrough: String
}
```

then the mutation becomes

```
CreatePlatform(platform: PlatformInput): Platform @cypher(statement: "CREATE (p:Platform) SET p = platform RETURN p")
```

and the input should be passed to the `@cypher` Cypher query as an object parameter. 

Could you give it a try and let us know if it works?

**Comment by johnymontana** [comment]
Closing as I hope the input type suggestion above worked. If that doesn't address your issue, please reopen.
