### ISSUE TITLE
Feature Request: Support Graphql Mutations 

### ISSUE THREAD

**Issue by 2wce** [neo4j-graphql/neo4j-graphql-js#9]
Hie, I love the work you've done so far. I was wondering if it would be possible to add mutations to the package as well. If the feature is already there can you please update the documentation to highlight how it works?

**Comment by johnymontana** [comment]
Hi @2wce! Thanks for trying out the package.

Currently, this package doesn't handle mutations. Adding mutations is next on my list of features to add. Hopefully, I'll get to it next week.

In the meantime you should be able to create mutation resolvers the standard way (writing Cypher queries to handle the write operations in the resolver).

**Comment by lazaruslarue** [comment]
Yeah... i'd love it if this would support mutations :) Wonderful tool

**Comment by aoighost** [comment]
Any word on this or how to implement in a PR?

**Comment by lazaruslarue** [comment]
@aoighost we've been writing our own `mutation` resolvers in the meantime. it's working pretty well. one strategy that I'm using is to use super simple mutation response payloads (e.g. just a "success" or "fail + error") and to write mutation queries like: `mutation {} query {}` such that the two are executed sequentially.

**Comment by bebbi** [comment]
@lazaruslarue that was an inspiring approach, thanks. I wanted to keep the problem in the back-end where it should eventually be solved, and also immediately directly use mutation results for the selectionSet.

What I ended up doing is tweaking the `resolveInfo` in the back-end to return the results directly after a query, so that it results in regular behaviour to the front-end.

This worked for me like the following:

1. define the correct return type for the mutation in the schema idl file
2. in the resolver, first write the custom mutation that returns a placeholder that's useful to look up the specific instance of the return type with. E.g.

        RETURN item { .id }

3. wait for that mutation to resolve and pass the result back to `neo4j-graphql-js` with a tweaked `resolveInfo` to inform the library about the query selectionSet. E.g. like this:

        const buildReturnValue = (mutationResult, context, resolveInfo) => {
          const newResolveInfo = Object.assign({}, resolveInfo, {
            // Replace the mutation name with the desired return type name
            fieldName: resolveInfo.returnType
          })
          const fieldNode = newResolveInfo.fieldNodes.find(
            f => f.name.value === resolveInfo.fieldName
          )
          // This is to associate the selectionSet with the correct type name.
          fieldNode.name.value = resolveInfo.returnType
          // The newResolveInfo is not consistent, but it's sufficient for neo4jgraphql
          // to do the right thing as the lib only looks at these fields.
          return neo4jgraphql(undefined, mutationResult, context, newResolveInfo)
        }

        // And in the resolver
        myMutation: async (object, params, context, resolveInfo) => {
          addDriver(context)
          const itemLookup = await myManualMutation()
          return buildReturnValue(itemLookup, context, resolveInfo)
        }

It's very hackish as the `newResolveInfo` is inconsistent, but if there's no better solution currently on the horizon something like this could probably be cleaned up and formalized into an approach to mutations in the lib. With the power of this lib, it could probably be done in a single roundtrip.

**Comment by johnymontana** [comment]
@bebbi, that's a clever approach! 

I started some initial work on generating Cypher for mutations in the `mutations` branch here 2ca321fbbec79f05ba8a47c1ea0706ccf755feb8

This should work for creating simple types (basically creating a node, not yet relationships), and including the correct `RETURN` clause based on the selection set specified. 

I'm curious though what you all would like to see for more complex mutation support. Especially around mutations that create relationships or more complex sub-graphs. What kind of input types would you expect to see supported? If anyone is willing to share how they are doing custom mutations now that would be helpful.

**Comment by bebbi** [comment]
An example of ours:

        // Create an item and connect it to an itemList.
        addItem(itemProps, listProps, currentUser)

Flow:

1. is the user authorized for this operation?
2. does the user own a previous list with the given listProps?
3. If yes, use existing list, if no, create new list using calculated and passed attributes, and make a relation to the user's node.
4. create a new item and attach to the list, using calculated and passed attributes.
5. return the new item.

Each 2 and 3-4 are a cypher query.
5 re-uses a `getItem` query.

**Comment by lazaruslarue** [comment]
@johnymontana 

here's a thing we do to make trees of component `(:Group)` & component `(:ComponentField)` a for a form that builds an tree of those on a `(:FormRecord)`.

some types of components in the fields get different details... such that the `:Field` nodes for 'TEXT INPUT'  `placeholder`

```
import * as uid from 'uuid/v4';
import integer from 'neo4j-driver/types/v1/integer';

export interface FormRecordPayload {
  uid: string;
  groups: GroupPayload[];
}

export interface GroupPayload {
  uid: string;
  index: number;
  fields: FieldPayload[];
}

export interface FieldPayload {
  uid: string;
  index: number;
  type: ComponentType;
}

enum ComponentType {
  TYPEONE = 'TYPEONE',
  TYPETWO = 'TYPETWO',
}

export interface TreeDto {
  uid: string;
  label: string;
  index: number;
  //  props?: TreePropsDto;
  relation?: string;
  type?: ComponentType;
  children?: TreeDto[];
}

export class BuildRecordTree {
  _queryString = '';

  constructor(record: FormRecordPayload) {
    let queryParts: string[] = [];

    // create the OG parent node
    const tree = {
      uid: uid(),
      label: 'FormRecord,
      relation: 'HAS_FORM_GROUP',
      children: record.groups.map(this.recordGroupsToDto)
    } as TreeDto;

    // create node from {parent+UID}
    queryParts.push(this.createNodeWithUid(tree, 'w'));

    // go over all parents
    // create nodes for {child+UID}
    tree.children
      .map(c => this.createNodeWithUid(c, 'g'))
      .forEach(q => queryParts.push(q));

    // merge each group to record
    tree.children
      .map(c =>
        this.mergeChildToParent(
          c,
          'w' + this.getPointer(tree),
          tree.relation,
          'g',
          c.index
        )
      )
      .forEach(q => queryParts.push(q));

    // for all groups
    tree.children.forEach(g => {
      // create a field node
      g.children
        .map(f => this.createNodeWithUid(f, 'f'))
        .forEach(q => queryParts.push(q));

      // merge field node to parent
      g.children
        .map(f =>
          this.mergeChildToParent(
            f,
            'g' + this.getPointer(g),
            g.relation,
            'f',
            f.index
          )
        )
        .forEach(q => queryParts.push(q));
    });


    queryParts.push(
      `RETURN ${'w' + this.getPointer(tree)} {.*} as formRecord`
    );

    this._queryString = queryParts.join('\n');
    // console.log(this._queryString);
  }

  private getPointer = (node: TreeDto) => node.uid.replace(/-/g, '');

  private recordGroupsToDto = (group: GroupPayload): TreeDto => {
    return {
      uid: uid(),
      label: 'RecordGroup',
      relation: 'HAS_FIELD',
      index: group.index,
      children: group.fields.map(this.fieldsToDto)
    };
  };

  private fieldsToDto = (field: FieldPayload): TreeDto => {
    return {
      uid: uid(),
      label: 'RecordField',
      type: field.type,
      index: field.index
    };
  };

  private createNodeWithUid(node: TreeDto, prefix: string): string {
    const pointer = '' + prefix + this.getPointer(node);
    let createString = `CREATE (${pointer}:${node.label}) 
        set ${pointer}.uid = "${node.uid}"  
        set ${pointer}.type = "${node.type}"
        set ${pointer}.index = "${node.index}"`;
    switch (node.type) {
      case 'TYPEONE':
        createString += ` set ${pointer}.type1_presetA = null`;
        createString += ` set ${pointer}.type1_presetB = null`;
        break;
      case 'TYPETWO':
        createString += ` set ${pointer}.type2_presetA = null`;
        createString += ` set ${pointer}.type2_presetB = null`;
        createString += ` set ${pointer}.type2_special_case_value = 5551212`;
        break;
      
    }

    return createString;
  }

  private mergeChildToParent(
    child: TreeDto,
    parent: string,
    relation: string,
    childPrefix: string,
    idx: number
  ): string {
    return `MERGE (${parent})-[:${relation} {created: timestamp(), index: ${idx}}]->(${childPrefix}${this.getPointer(
      child
    )}) `;
  }

  get query(): string {
    return this._queryString;
  }
}
```

**Comment by cooperka** [comment]
I like the concept behind @bebbi's solution but it didn't seem to work for me. This alternative is much simpler and might be all that's needed for basic mutations. Simply grab the object from the response:

```js
const result = await session.run(
  'CREATE (item:User {name: $name}) RETURN item',
  { name: 'Kevin' },
);

return result.records[0]._fields[0].properties;
```

e.g. this will return the new User for GraphQL to consume:

```js
{
  name: 'Kevin',
}
```

**Comment by johnymontana** [comment]
Hey folks - just wanted to provide an update here on the status of mutation support.

We've added an `augmentSchema` function that can be called to add auto-generated create, update, and delete mutations to the schema (these are inferred from the existing typedefs in the schema). There is an example [here](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/example/apollo-server/movies-middleware.js#L18)

I'm currently working on adding documentation explaining more, but the mutations generally mirror those generated in the [neo4j-graphql database plugin](https://github.com/neo4j-graphql/neo4j-graphql#auto-generated-mutations).

We've already had a few requests for supporting nested mutations, but please add feedback here if you have a chance to test.

**Comment by AaronCremona** [comment]
@johnymontana This is an exciting development. I have had the chance to spin up a small example and have successfully done some simple mutations. 

Question:  Are simple relationships possible in the current form? Eg Create (NewNode) -[:loves]- (ExistingNode). I don't see the relevant arguments in the Graphql Playground Schema explorer.

**Comment by johnymontana** [comment]
Hey folks - now that we've iterated a bit on generated mutations I wanted to update this thread to make sure everyone is aware the library now supports: 1) auto-generated create, update, delete mutations for node and relationship types and 2) [`@cypher` directive](https://grandstack.io/docs/neo4j-graphql-js.html#cypher-directive) defined mutations.

The auto-generated mutations can be added to the schema by calling either [`makeExecutableSchema`](https://grandstack.io/docs/neo4j-graphql-js-api.html#makeaugmentedschemaoptions-graphqlschema) and passing type definitions, or [`augmentSchema`](https://grandstack.io/docs/neo4j-graphql-js-api.html#augmentschemaschema-config-graphqlschema) in the case of an already existing GraphQLSchema object. See the [docs here.](https://grandstack.io/docs/neo4j-graphql-js.html#generated-mutations)

**Comment by daghan** [comment]
Hey @johnymontana - I love the autogenerate feature. For add / remove mutations for relations, they work great if [`astNode.kind === 'ObjectTypeDefinition' `](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/src/utils.js#L252).
Is there a way to autogenerate add / remove mutations for relationships if `astNode.kind === 'InterfaceTypeDefinition`
