### ISSUE TITLE
access properties of relations?

### ISSUE THREAD

**Issue by stephen-dahl** [neo4j-graphql/neo4j-graphql-js#97]
given the schema
`(Cart) --[hasItem]->(Item)`
how would you get the `quantity` property from the relation `hasItem`?
```
type Cart {
    items: [Item]
    ...
}
type Item {
    name: String!
    description: String!
    price: Float!
    ...
}
type hasItem {
   quantity: Int!
}
```

**Comment by johnymontana** [comment]
Hey @stephen-dahl we've recently added better relationship type support in v1.0.x. For your example, try

```
type Cart {
  items: [CartItems]
  
}

type Item {
  name: String!
  description: String!
  price: Float!
}

type CartItems @relation(name:"HAS_ITEM") {
  from: Cart
  to: Item
  quantity: Int!
}

```

If you contruct your schema using `makeAugmentedSchema` (or `augmentSchema`) you'll see autogenerated Query and Mutation types for basic CRUD. In your case to access `quantity` your GraphQL query would look something like:

```
Cart {
  items {
    quantity
    Item {
      name
      description
     }
  }
}
```

Please give it a try and let us know how it works!

See the docs on this here: https://grandstack.io/docs/neo4j-graphql-js.html#relationship-types
